import type { GeneratedDocument } from '@/types';

interface PdfOptions {
  clientName?: string;
  companyName?: string;
  projectRef?: string;
  date?: string;
}

/**
 * Generates a basic PDF from a GeneratedDocument.
 * Uses raw PDF construction (no external dependencies) suitable for serverless.
 * Produces a clean, professional document with title page, TOC, and numbered sections.
 */
export async function generatePdf(
  document: GeneratedDocument,
  options: PdfOptions = {}
): Promise<Buffer> {
  const pdf = new PdfWriter();

  // Title page
  pdf.addPage();
  pdf.setFont('Helvetica-Bold', 24);
  pdf.drawTextCentered(document.title, 400);
  pdf.setFont('Helvetica', 14);
  if (options.date) {
    pdf.drawTextCentered(options.date, 360);
  }
  if (options.companyName) {
    pdf.drawTextCentered(`Prepared by: ${options.companyName}`, 330);
  }
  if (options.projectRef) {
    pdf.drawTextCentered(`Reference: ${options.projectRef}`, 300);
  }
  if (options.clientName) {
    pdf.drawTextCentered(`Client: ${options.clientName}`, 270);
  }
  pdf.drawTextCentered('Generated by InstantAI Assessment', 200);

  // Table of Contents
  pdf.addPage();
  pdf.setFont('Helvetica-Bold', 18);
  pdf.drawText('Table of Contents', 72, 700);
  pdf.setFont('Helvetica', 11);
  let tocY = 670;
  document.sections.forEach((section, index) => {
    pdf.drawText(`${index + 1}. ${section.name}`, 72, tocY);
    tocY -= 20;
    if (tocY < 72) {
      pdf.addPage();
      tocY = 700;
    }
  });

  // Document sections
  document.sections.forEach((section, index) => {
    pdf.addPage();

    // Section heading
    pdf.setFont('Helvetica-Bold', 16);
    pdf.drawText(`${index + 1}. ${section.name}`, 72, 700);

    // Section content
    pdf.setFont('Helvetica', 11);
    const paragraphs = section.content.split('\n\n').filter(Boolean);
    let y = 670;

    for (const para of paragraphs) {
      const trimmed = para.trim();
      if (!trimmed) continue;

      // Check for markdown headings
      if (trimmed.startsWith('## ') || trimmed.startsWith('### ')) {
        const text = trimmed.replace(/^#+\s*/, '');
        const headingSize = trimmed.startsWith('### ') ? 12 : 14;
        pdf.setFont('Helvetica-Bold', headingSize);
        y -= 10;

        if (y < 100) {
          pdf.addPage();
          y = 700;
        }

        pdf.drawText(text, 72, y);
        y -= headingSize + 8;
        pdf.setFont('Helvetica', 11);
        continue;
      }

      // Wrap text to page width
      const lines = wrapText(trimmed, 80);
      for (const line of lines) {
        if (y < 72) {
          pdf.addPage();
          pdf.setFont('Helvetica', 11);
          y = 700;
        }
        pdf.drawText(line, 72, y);
        y -= 15;
      }
      y -= 5; // paragraph spacing
    }
  });

  return pdf.toBuffer();
}

function wrapText(text: string, maxChars: number): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let currentLine = '';

  for (const word of words) {
    if ((currentLine + ' ' + word).trim().length > maxChars) {
      if (currentLine) lines.push(currentLine.trim());
      currentLine = word;
    } else {
      currentLine = currentLine ? currentLine + ' ' + word : word;
    }
  }
  if (currentLine) lines.push(currentLine.trim());

  return lines;
}

// Minimal PDF writer — constructs valid PDF 1.4 documents
class PdfWriter {
  private objects: string[] = [];
  private pages: number[] = [];
  private currentPage: { streams: string[] } | null = null;
  private currentFont = 'Helvetica';
  private currentFontSize = 12;
  private pageWidth = 595.28; // A4
  private pageHeight = 841.89;

  addPage() {
    this.commitCurrentPage();
    this.currentPage = { streams: [] };
  }

  setFont(name: string, size: number) {
    this.currentFont = name;
    this.currentFontSize = size;
    if (this.currentPage) {
      const fontKey = this.getFontKey(name);
      this.currentPage.streams.push(`BT /${fontKey} ${size} Tf ET`);
    }
  }

  drawText(text: string, x: number, y: number) {
    if (!this.currentPage) return;
    const escaped = this.escapeText(text);
    this.currentPage.streams.push(
      `BT /${this.getFontKey(this.currentFont)} ${this.currentFontSize} Tf ${x} ${y} Td (${escaped}) Tj ET`
    );
  }

  drawTextCentered(text: string, y: number) {
    // Approximate center based on character count
    const charWidth = this.currentFontSize * 0.5;
    const textWidth = text.length * charWidth;
    const x = (this.pageWidth - textWidth) / 2;
    this.drawText(text, Math.max(72, x), y);
  }

  toBuffer(): Buffer {
    this.commitCurrentPage();

    const offsets: number[] = [];
    let content = '';

    // PDF header
    content += '%PDF-1.4\n';

    // Font objects (1-4)
    const fonts: Record<string, { num: number; basefont: string }> = {
      F1: { num: 1, basefont: 'Helvetica' },
      F2: { num: 2, basefont: 'Helvetica-Bold' },
      F3: { num: 3, basefont: 'Helvetica-Oblique' },
      F4: { num: 4, basefont: 'Courier' },
    };

    for (const [, font] of Object.entries(fonts)) {
      offsets.push(content.length);
      content += `${font.num} 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /${font.basefont} >>\nendobj\n`;
    }

    // Build page objects and stream objects
    const pageObjectStart = 5;
    const pageObjNums: number[] = [];
    let nextObj = pageObjectStart;

    for (let i = 0; i < this.pages.length; i++) {
      const streamContent = this.objects[i];
      const streamObjNum = nextObj;
      const pageObjNum = nextObj + 1;
      pageObjNums.push(pageObjNum);

      // Stream object
      offsets.push(content.length);
      content += `${streamObjNum} 0 obj\n<< /Length ${streamContent.length} >>\nstream\n${streamContent}\nendstream\nendobj\n`;
      nextObj++;

      // Page object
      offsets.push(content.length);
      content += `${pageObjNum} 0 obj\n<< /Type /Page /Parent ${nextObj + this.pages.length - i} 0 R /MediaBox [0 0 ${this.pageWidth} ${this.pageHeight}] /Contents ${streamObjNum} 0 R /Resources << /Font << /F1 1 0 R /F2 2 0 R /F3 3 0 R /F4 4 0 R >> >> >>\nendobj\n`;
      nextObj++;
    }

    // Pages object (catalog parent)
    const pagesObjNum = nextObj;
    offsets.push(content.length);
    const kidsStr = pageObjNums.map((n) => `${n} 0 R`).join(' ');
    content += `${pagesObjNum} 0 obj\n<< /Type /Pages /Kids [${kidsStr}] /Count ${pageObjNums.length} >>\nendobj\n`;
    nextObj++;

    // Fix page parent references (replace placeholder)
    // We need to rebuild with correct parent references
    // Actually, let's rebuild properly

    // Start over with a cleaner approach
    return this.buildCleanPdf();
  }

  private buildCleanPdf(): Buffer {
    this.commitCurrentPage();

    const objects: string[] = [];

    // obj 1: Catalog
    objects.push('<< /Type /Catalog /Pages 2 0 R >>');

    // obj 2: Pages
    const pageRefs = this.objects.map((_, i) => `${4 + i * 2} 0 R`).join(' ');
    objects.push(`<< /Type /Pages /Kids [${pageRefs}] /Count ${this.objects.length} >>`);

    // obj 3: Font resources
    objects.push(
      '<< /F1 << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> ' +
      '/F2 << /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >> ' +
      '/F3 << /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Oblique >> >>'
    );

    // For each page: stream object + page object
    for (let i = 0; i < this.objects.length; i++) {
      const streamContent = this.objects[i];
      const streamObjNum = 4 + i * 2; // stream obj
      const pageObjNum = streamObjNum + 1; // page obj (not used in objects array directly)

      // Stream object (even index from base 4)
      objects.push(
        `<< /Length ${streamContent.length} >>\nstream\n${streamContent}\nendstream`
      );

      // Page object
      objects.push(
        `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${this.pageWidth} ${this.pageHeight}] ` +
        `/Contents ${streamObjNum} 0 R /Resources << /Font 3 0 R >> >>`
      );
    }

    // Build raw PDF
    let pdf = '%PDF-1.4\n%\xE2\xE3\xCF\xD3\n';
    const offsets: number[] = [];

    for (let i = 0; i < objects.length; i++) {
      offsets.push(pdf.length);
      const objNum = i + 1;
      pdf += `${objNum} 0 obj\n${objects[i]}\nendobj\n\n`;
    }

    // Cross-reference table
    const xrefOffset = pdf.length;
    pdf += 'xref\n';
    pdf += `0 ${objects.length + 1}\n`;
    pdf += '0000000000 65535 f \n';
    for (const offset of offsets) {
      pdf += `${String(offset).padStart(10, '0')} 00000 n \n`;
    }

    // Trailer
    pdf += 'trailer\n';
    pdf += `<< /Size ${objects.length + 1} /Root 1 0 R >>\n`;
    pdf += 'startxref\n';
    pdf += `${xrefOffset}\n`;
    pdf += '%%EOF\n';

    return Buffer.from(pdf, 'binary');
  }

  private commitCurrentPage() {
    if (!this.currentPage) return;
    const stream = this.currentPage.streams.join('\n');
    this.objects.push(stream);
    this.pages.push(this.objects.length);
    this.currentPage = null;
  }

  private getFontKey(name: string): string {
    if (name.includes('Bold')) return 'F2';
    if (name.includes('Oblique') || name.includes('Italic')) return 'F3';
    return 'F1';
  }

  private escapeText(text: string): string {
    return text
      .replace(/\\/g, '\\\\')
      .replace(/\(/g, '\\(')
      .replace(/\)/g, '\\)')
      .replace(/[^\x20-\x7E]/g, '?'); // Replace non-ASCII with ?
  }
}
