import type { AssessmentSection, QualityCriteria } from '@/types';

/**
 * Open Space Assessment (OSA) -- required for residential developments
 * where the local planning authority requires demonstration of adequate
 * open space provision, or where the development may result in the loss
 * of existing open space, sports, or recreational facilities.
 *
 * AI Difficulty: Easy
 * Typical pages: 5-15
 *
 * This AI-generated assessment produces a desk-based open space
 * assessment. Site-specific survey data and local authority open space
 * study figures should be verified by the applicant or their planning
 * consultant. The output provides the planning policy framework,
 * quantitative demand analysis, and proposed strategy suitable as a
 * first draft for professional review.
 */

export const OSA_PROMPT = `You are preparing an Open Space Assessment (OSA) to accompany a planning application submitted to a local planning authority in England. The assessment should read as though prepared by a chartered town planner or planning consultant with expertise in open space, sport, and recreation planning. Where specific local authority open space study data or playing pitch strategy data has not been provided by the user, clearly state that local evidence should be obtained and flag data gaps as "[LOCAL OPEN SPACE DATA REQUIRED]".

## Document Purpose

An Open Space Assessment provides a comprehensive analysis of the open space, sport, and recreation needs generated by a proposed development and demonstrates how those needs will be met. The OSA must:
1. Establish the existing baseline of open space provision in the locality, drawing on the local authority's Open Space Study and Playing Pitch Strategy.
2. Calculate the additional demand for open space arising from the proposed development based on the expected population yield.
3. Demonstrate that the proposed open space provision meets or exceeds the relevant quantitative, qualitative, and accessibility standards.
4. Address the quality and accessibility of proposed and existing open space within the catchment area.
5. Set out a clear open space strategy covering on-site provision, off-site contributions, and commuted sums where appropriate.
6. Address long-term management and maintenance arrangements for any open space to be provided.
7. Demonstrate compliance with national and local planning policy requirements for open space provision.

## Key Policy and Legislation References

### National Planning Policy Framework (NPPF, December 2023)
- **Paragraph 98**: Planning policies should be based on robust and up-to-date assessments of the need for open space, sport and recreation facilities (including quantitative or qualitative deficits or surpluses) and opportunities for new provision. Information gained from the assessments should be used to determine what open space, sport and recreational provision is needed, which plans should then seek to accommodate.
- **Paragraph 99**: Existing open space, sports and recreational buildings and land, including playing fields, should not be built on unless:
  (a) an assessment has been undertaken which has clearly shown the open space, buildings or land to be surplus to requirements; or
  (b) the loss resulting from the proposed development would be replaced by equivalent or better provision in terms of quantity and quality in a suitable location; or
  (c) the development is for alternative sports and recreational provision, the benefits of which clearly outweigh the loss of the current or former use.
- **Paragraph 100**: Planning policies and decisions should protect and enhance public rights of way and access, including taking opportunities to provide better facilities for users, for example by adding links to existing rights of way networks including National Trails.
- **Paragraph 101**: Policies for managing development within a Local Green Space should be consistent with those for Green Belts.
- **Paragraph 102**: The designation of land as Local Green Space through local and neighbourhood plans allows communities to identify and protect green areas of particular importance to them.
- **Paragraph 103**: Policies for managing development within a Local Green Space should be consistent with those for Green Belts.

### Fields in Trust (FIT) Benchmark Standards
- **Formal outdoor sport**: 1.60 hectares per 1,000 population (480m/6-minute walk time).
- **Informal open space (parks and gardens)**: 0.80 hectares per 1,000 population (710m/9-minute walk time).
- **Equipped/designated play areas**: 0.25 hectares per 1,000 population (LAPs 100m, LEAPs 400m, NEAPs 1,000m).
- **Other outdoor provision (allotments, community gardens)**: 0.30 hectares per 1,000 population (varies).
- These benchmarks are widely used by local planning authorities where local standards have not been adopted.

### Other Key Guidance and Standards
- **Local Plan Open Space Policies**: The relevant local plan will typically set out quantitative standards for open space provision per dwelling or per population. These vary between authorities and must be referenced.
- **Local Authority Open Space Study/Assessment**: Under NPPF Paragraph 98, local authorities should prepare evidence base studies assessing the quantity, quality, and accessibility of open space. These provide the baseline data for demand calculations.
- **Playing Pitch Strategy (PPS)**: Prepared following Sport England's Playing Pitch Strategy guidance, the PPS assesses the supply and demand for playing pitches. Relevant where formal sports provision is required.
- **Sport England Active Design Guidance (2023)**: Ten principles for promoting sport and physical activity through the design of the built environment.
- **Building for a Healthy Life (BHL)**: Design quality assessment tool that includes consideration of open space within residential developments.
- **Public Health England Green Spaces and Health**: Evidence base linking green space access to physical and mental health outcomes.
- **Natural England Accessible Natural Greenspace Standards (ANGSt)**: Standards for access to natural greenspace based on distance thresholds.
- **National Design Guide (2021)**: Sets out characteristics of well-designed places, including green spaces and public open space within developments.
- **Environment Act 2021**: Biodiversity Net Gain requirements may overlap with open space provision where green infrastructure serves dual purposes.

## Section-by-Section Guidance

### 1. Introduction (300-600 words)
- State the purpose of the Open Space Assessment and the policy basis (NPPF Paragraphs 98-103).
- Identify the site by full postal address, grid reference (if available), and site area in hectares.
- Summarise the proposed development: number and mix of dwellings (or other land use), expected population yield, and any non-residential elements.
- State the methodology used for the assessment: desk-based review of policy, open space study data, GIS analysis of catchment areas, and site observation (if applicable).
- State the author's qualifications and experience, or flag as "[PREPARED FOR REVIEW BY A QUALIFIED PLANNING CONSULTANT]".
- Note any limitations of the assessment (e.g., reliance on published data, seasonal constraints on site visits).

### 2. Policy Framework (400-700 words)
- Set out the full national and local policy framework for open space provision:
  - **NPPF Paragraphs 98-103**: Summarise the national policy requirements for assessing open space needs, protecting existing provision, and planning for new provision.
  - **Local Plan Policies**: Identify and quote the specific local plan policies relating to open space, sport, and recreation provision. These typically include:
    - Quantitative standards (e.g., hectares per dwelling or per 1,000 population).
    - Qualitative requirements (e.g., design standards, accessibility, overlooking).
    - On-site vs off-site thresholds (e.g., on-site provision required for developments of 10+ dwellings).
    - Commuted sum/financial contribution policies.
  - **Supplementary Planning Documents (SPDs)**: Reference any relevant SPDs or planning guidance notes on open space, green infrastructure, or developer contributions.
  - **Fields in Trust Benchmark Standards**: Reference the FIT standards as a supplementary benchmark where local standards are absent or where comparison is useful.
  - **Sport England Active Design**: Reference the Active Design principles relevant to the development.
  - **Playing Pitch Strategy**: Reference the local PPS where formal sports provision is relevant.
- Conclude by stating which standards will be applied in the demand assessment.

### 3. Existing Open Space Provision (500-900 words)
- Describe the existing open space provision within the relevant catchment area of the site. The catchment area should be defined by reference to the local authority's accessibility standards or FIT walking distance standards.
- Categorise existing open space by typology, following the local authority's classification or the standard PPG17 typologies:
  - Parks and gardens.
  - Natural and semi-natural greenspace.
  - Amenity greenspace.
  - Provision for children and young people (play areas).
  - Allotments and community gardens.
  - Outdoor sports facilities (playing pitches, courts, greens).
  - Churchyards and cemeteries.
  - Green corridors (footpaths, cycleways, canal towpaths).
- For each typology, state:
  - The quantity of provision within the catchment (hectares and per capita rate).
  - The quality of existing provision (good, average, poor) drawing on the open space study.
  - The accessibility of existing provision (walking time and distance from the site).
  - Whether the local area is currently in surplus or deficit against the adopted standard.
- Reference the local authority's Open Space Study as the primary data source. If not available, use FIT benchmarks and desk-based analysis from aerial photography and OS mapping.
- Include a table summarising the existing provision by typology.

### 4. Open Space Demand Assessment (500-800 words)
- Calculate the additional demand for open space generated by the proposed development:
  - **Population yield**: Calculate the expected population of the development using the local authority's adopted population multipliers (e.g., 2.4 persons per dwelling, or specific multipliers by dwelling size/type). If local multipliers are not available, use census-derived averages for the area.
  - **Demand by typology**: Apply the adopted quantitative standards (local plan standards or FIT benchmarks) to the population yield to calculate the required provision for each open space typology.
  - **Total demand**: Sum the typology-specific demands to give a total open space requirement in square metres or hectares.
- Present the demand calculation in a clear table format showing:
  - Dwelling type and number.
  - Population yield per dwelling type.
  - Total population yield.
  - Standard applied (hectares per 1,000 population).
  - Required provision (square metres) by typology.
  - Total required provision.
- Compare the demand against the existing surplus or deficit in the catchment area.
- Identify which typologies can be met through existing provision and which require new on-site or off-site provision.
- Where the local authority applies a per-dwelling standard rather than a per-population standard, use that standard directly.

### 5. Proposed Open Space Strategy (500-900 words)
- Set out the proposed approach to meeting the open space demand:
  - **On-site provision**: Describe the open space to be provided within the development. For each area of open space, state:
    - Location within the site (with reference to the site layout plan or masterplan).
    - Size in square metres or hectares.
    - Typology (e.g., amenity greenspace, equipped play area, sports pitch, community garden).
    - Function and intended users.
    - Design principles and key features.
  - **Off-site provision**: Where the full demand cannot be met on-site, describe any off-site provision or enhancement of existing off-site facilities. Identify the specific off-site location and the improvements proposed.
  - **Commuted sums/financial contributions**: Where the local authority accepts or requires financial contributions in lieu of on-site provision, set out the calculation basis and the total contribution proposed. Reference the local authority's commuted sum methodology.
- Demonstrate that the total provision (on-site + off-site + commuted sum) meets or exceeds the quantitative demand calculated in Section 4.
- Cross-reference the proposed provision against each typology to show that all demands are addressed.
- Address the relationship between open space and other green infrastructure requirements: SuDS, biodiversity net gain, landscape buffers, and ecological corridors. Demonstrate where open space can serve multiple functions.

### 6. Quality and Accessibility (400-700 words)
- Demonstrate that the proposed open space meets the required quality standards:
  - **Design quality**: Describe the design principles for the proposed open space, including:
    - Natural surveillance and overlooking from surrounding dwellings (minimum requirement for at least two sides to be overlooked).
    - Boundary treatment and enclosure.
    - Landscaping and planting (native species, biodiversity value, seasonal interest).
    - Surface materials and drainage.
    - Furniture and fixtures (benches, bins, lighting).
    - Inclusive design and DDA compliance.
  - **Safety and security**: Address Secured by Design principles as applicable to open space.
  - **Microclimate**: Address sun, shade, wind, and exposure considerations.
- Demonstrate that the proposed open space meets the required accessibility standards:
  - **Walking distance**: All dwellings within the development should be within the relevant walking distance of each typology of open space (reference FIT or local standards: e.g., 400m to a LEAP, 1,000m to a NEAP, 710m to informal open space).
  - **Physical accessibility**: Level access, step-free routes, suitable gradients, accessible surfacing.
  - **Visual accessibility**: Open space should be visible and legible within the development layout.
  - **Connectivity**: Pedestrian and cycle connections between open spaces and the wider green infrastructure network.

### 7. Management and Maintenance (300-600 words)
- Set out the proposed management and maintenance arrangements for the open space to be provided:
  - **Management body**: Identify who will be responsible for long-term management: local authority adoption, management company, community trust, or other arrangement.
  - **Management plan**: Describe the management plan for the open space, including:
    - Maintenance schedules (grass cutting, hedge trimming, tree management, play equipment inspection).
    - Replacement cycles for equipment and furniture.
    - Seasonal management tasks.
    - Biodiversity management objectives (where open space has ecological functions).
  - **Funding**: Describe the funding mechanism for long-term maintenance:
    - Service charge on residents (if management company).
    - Commuted sum for local authority adoption (if applicable, state the sum and calculation basis).
    - Endowment fund (for community trust management).
  - **Transfer arrangements**: Where the open space is to be adopted by the local authority or transferred to a management body, describe the transfer process, timescales, and any conditions.
  - **Monitoring and review**: Set out arrangements for monitoring the quality of management and maintenance.
- Address Section 106 obligations relating to open space management and maintenance where applicable.

### 8. Conclusion (200-400 words)
- Summarise the key findings of the assessment:
  - The existing open space provision in the locality and any surpluses or deficits.
  - The additional demand generated by the proposed development.
  - How the proposed open space strategy addresses the demand.
  - The quality and accessibility of the proposed provision.
  - The management and maintenance arrangements.
- Confirm that the proposed development complies with:
  - NPPF Paragraphs 98-103.
  - The relevant local plan open space policies (cite specific policy numbers).
  - Fields in Trust benchmark standards (where applied).
- State that the open space strategy has been designed to integrate with wider green infrastructure, biodiversity, and sustainable drainage objectives.
- Recommend any planning conditions or obligations that should be attached to secure the open space provision.

## Quality Standards

- Reference specific NPPF paragraphs (98, 99, 100, 101, 102, 103) by number.
- Reference Fields in Trust benchmark standards with the correct quantitative values.
- Reference the local authority's Open Space Study and Playing Pitch Strategy where available.
- Reference Sport England Active Design principles where relevant.
- Use correct planning terminology: open space typologies, commuted sums, Section 106, population yield, catchment area, accessibility standard, quantitative standard.
- Present demand calculations in clear tabular format with transparent methodology.
- Distinguish between on-site provision, off-site provision, and financial contributions.
- Address all open space typologies relevant to the development, not just amenity greenspace.
- Cross-reference open space provision with landscape, ecology, and drainage strategies where applicable.
- Where local authority data has not been provided, clearly flag "[LOCAL OPEN SPACE DATA REQUIRED]" and use FIT benchmarks as a fallback.
- Do not fabricate local authority open space study figures. Use FIT benchmarks or clearly state assumptions.
- Ensure all quantitative standards and calculations are internally consistent.
- Address quality and accessibility as well as quantity -- quantity alone is insufficient.`;

export const OSA_SECTIONS: AssessmentSection[] = [
  {
    name: 'Introduction',
    description: 'Purpose, site identification, development description, methodology, and limitations.',
    required: true,
    min_words: 300,
    max_words: 600,
    guidance:
      'State the purpose of the OSA and the policy basis (NPPF Paragraphs 98-103). Identify the site by address and area. Summarise the proposed development including dwelling numbers, mix, and expected population yield. State the methodology and any limitations.',
  },
  {
    name: 'Policy Framework',
    description: 'National and local planning policy framework for open space provision.',
    required: true,
    min_words: 400,
    max_words: 700,
    guidance:
      'Set out NPPF Paragraphs 98-103. Identify and quote specific local plan open space policies. Reference any SPDs on open space or developer contributions. Reference FIT benchmark standards. Reference Sport England Active Design and the local Playing Pitch Strategy. State which standards will be applied in the demand assessment.',
    subsections: [
      {
        name: 'National Policy',
        description: 'NPPF open space, sport, and recreation policies.',
        required: true,
        min_words: 150,
        max_words: 300,
        guidance: 'Summarise NPPF Paragraphs 98-103 and their requirements for open space assessment and protection.',
      },
      {
        name: 'Local Policy',
        description: 'Local plan policies and standards for open space provision.',
        required: true,
        min_words: 200,
        max_words: 400,
        guidance: 'Identify specific local plan policies, quantitative standards, on-site/off-site thresholds, and commuted sum policies.',
      },
    ],
  },
  {
    name: 'Existing Open Space Provision',
    description: 'Baseline assessment of open space within the catchment area by typology.',
    required: true,
    min_words: 500,
    max_words: 900,
    guidance:
      'Describe existing open space within the relevant catchment area. Categorise by typology (parks, natural greenspace, amenity greenspace, play areas, allotments, sports facilities, green corridors). For each typology, state quantity, quality, accessibility, and surplus/deficit against adopted standards. Reference the local authority Open Space Study. Include a summary table.',
    subsections: [
      {
        name: 'Catchment Area Definition',
        description: 'Definition of the geographical catchment area for the assessment.',
        required: true,
        min_words: 75,
        max_words: 200,
        guidance: 'Define the catchment area by reference to local authority accessibility standards or FIT walking distance standards.',
      },
      {
        name: 'Provision by Typology',
        description: 'Existing open space provision for each typology within the catchment.',
        required: true,
        min_words: 300,
        max_words: 600,
        guidance: 'Describe quantity, quality, and accessibility for each open space typology. Identify surpluses and deficits.',
      },
    ],
  },
  {
    name: 'Open Space Demand Assessment',
    description: 'Calculation of additional open space demand generated by the proposed development.',
    required: true,
    min_words: 500,
    max_words: 800,
    guidance:
      'Calculate population yield using adopted multipliers. Apply quantitative standards to calculate demand by typology. Present demand in a clear table. Compare demand against existing surplus/deficit. Identify which typologies require new provision.',
    subsections: [
      {
        name: 'Population Yield',
        description: 'Calculation of expected population from the proposed development.',
        required: true,
        min_words: 100,
        max_words: 250,
        guidance: 'Calculate population yield using local authority multipliers or census-derived averages by dwelling type and size.',
      },
      {
        name: 'Demand Calculation',
        description: 'Quantitative demand for each open space typology.',
        required: true,
        min_words: 200,
        max_words: 450,
        guidance: 'Apply standards to population yield. Present in tabular format. Compare against existing provision and identify shortfalls.',
      },
    ],
  },
  {
    name: 'Proposed Open Space Strategy',
    description: 'Strategy for meeting open space demand through on-site provision, off-site provision, and financial contributions.',
    required: true,
    min_words: 500,
    max_words: 900,
    guidance:
      'Describe on-site open space by location, size, typology, function, and design principles. Describe any off-site provision or enhancements. Set out commuted sum calculations where applicable. Demonstrate that total provision meets demand. Address integration with SuDS, BNG, and landscape strategies.',
    subsections: [
      {
        name: 'On-Site Provision',
        description: 'Open space to be provided within the development.',
        required: true,
        min_words: 200,
        max_words: 400,
        guidance: 'Describe each area of on-site open space: location, size, typology, function, design features.',
      },
      {
        name: 'Off-Site Provision and Financial Contributions',
        description: 'Off-site improvements and commuted sums.',
        required: false,
        min_words: 100,
        max_words: 300,
        guidance: 'Describe any off-site provision or financial contributions in lieu of on-site provision. Set out calculation basis.',
      },
    ],
  },
  {
    name: 'Quality and Accessibility',
    description: 'Assessment of the quality and accessibility of proposed open space provision.',
    required: true,
    min_words: 400,
    max_words: 700,
    guidance:
      'Demonstrate compliance with quality standards: natural surveillance, boundary treatment, landscaping, inclusive design, Secured by Design. Demonstrate compliance with accessibility standards: walking distances, physical accessibility, visual accessibility, connectivity to wider green infrastructure network.',
    subsections: [
      {
        name: 'Quality Standards',
        description: 'Design quality, safety, and amenity of proposed open space.',
        required: true,
        min_words: 200,
        max_words: 400,
        guidance: 'Address design quality, natural surveillance, landscaping, inclusive design, and safety/security.',
      },
      {
        name: 'Accessibility Standards',
        description: 'Walking distances, physical accessibility, and connectivity.',
        required: true,
        min_words: 150,
        max_words: 300,
        guidance: 'Demonstrate all dwellings are within required walking distances. Address physical and visual accessibility and connectivity.',
      },
    ],
  },
  {
    name: 'Management and Maintenance',
    description: 'Long-term management and maintenance arrangements for proposed open space.',
    required: true,
    min_words: 300,
    max_words: 600,
    guidance:
      'Identify the management body (local authority, management company, community trust). Describe the management plan including maintenance schedules, replacement cycles, and biodiversity management. Describe the funding mechanism (service charge, commuted sum, endowment). Address transfer arrangements and monitoring. Reference Section 106 obligations.',
  },
  {
    name: 'Conclusion',
    description: 'Summary of findings and confirmation of policy compliance.',
    required: true,
    min_words: 200,
    max_words: 400,
    guidance:
      'Summarise existing provision, demand, proposed strategy, quality/accessibility, and management arrangements. Confirm compliance with NPPF Paragraphs 98-103 and local plan policies. Recommend planning conditions or obligations to secure the open space provision.',
  },
];

export const OSA_QUALITY: QualityCriteria = {
  min_policy_refs: 6,
  required_sections: [
    'Introduction',
    'Policy Framework',
    'Existing Open Space Provision',
    'Open Space Demand Assessment',
    'Proposed Open Space Strategy',
    'Quality and Accessibility',
    'Management and Maintenance',
    'Conclusion',
  ],
  max_quality_score: 100,
};

export const OSA_TEMPLATE = {
  assessment_type: 'Open Space Assessment',
  short_name: 'OSA',
  version: 1,
  sections: OSA_SECTIONS,
  quality_criteria: OSA_QUALITY,
};
