import type { AssessmentSection, QualityCriteria } from '@/types';

/**
 * Play Space Assessment (PSA) -- required for residential developments
 * where the local planning authority requires demonstration of adequate
 * play space provision for children and young people, typically triggered
 * by developments of 10+ dwellings or those generating a child yield.
 *
 * AI Difficulty: Easy
 * Typical pages: 5-10
 *
 * This AI-generated assessment produces a desk-based play space
 * assessment. Child yield data and local authority play space standards
 * should be verified by the applicant or their planning consultant.
 * The output provides the planning policy framework, child yield
 * calculations, and proposed play strategy suitable as a first draft
 * for professional review.
 */

export const PSA_PROMPT = `You are preparing a Play Space Assessment (PSA) to accompany a planning application submitted to a local planning authority in England. The assessment should read as though prepared by a chartered town planner, landscape architect, or planning consultant with expertise in play space planning and design. Where specific local authority child yield data, play space standards, or play strategy data has not been provided by the user, clearly state that local evidence should be obtained and flag data gaps as "[LOCAL PLAY SPACE DATA REQUIRED]".

## Document Purpose

A Play Space Assessment provides a detailed analysis of the play space needs generated by a proposed residential development and demonstrates how those needs will be met through age-appropriate, accessible, and well-designed play provision. The PSA must:
1. Calculate the child yield of the proposed development based on the dwelling mix and local authority child yield multipliers.
2. Establish the existing baseline of play space provision in the locality, identifying the type, quality, and accessibility of existing facilities.
3. Calculate the quantum of play space required to serve the development based on adopted local standards.
4. Set out a play strategy that provides age-appropriate play opportunities for all age groups of children and young people.
5. Demonstrate that the play space design meets current best practice standards for inclusive, imaginative, and nature-based play.
6. Address management and maintenance of the proposed play spaces.
7. Demonstrate compliance with national and local planning policy requirements for play provision.

## Key Policy and Legislation References

### National Planning Policy Framework (NPPF, December 2023)
- **Paragraph 98**: Planning policies should be based on robust and up-to-date assessments of the need for open space, sport and recreation facilities (including quantitative or qualitative deficits or surpluses) and opportunities for new provision. This includes provision for children and young people.
- **Paragraph 99**: Existing open space, sports and recreational buildings and land, including playing fields, should not be built on unless the tests in (a), (b), or (c) are met. Play spaces fall within this protection.
- **Paragraph 100**: Planning policies and decisions should protect and enhance public rights of way and access, including taking opportunities to provide better facilities for users.
- **Paragraph 130** (design quality): Planning policies and decisions should ensure that developments are visually attractive, function well, and are sympathetic to local character. Play spaces should be well-integrated into the development layout.

### London Plan (2021) -- For London Boroughs
- **Policy S4 (Play and Informal Recreation)**: Requires development proposals that include housing to make provision for play and informal recreation based on the expected child population generated by the scheme and an assessment of future needs.
  - A minimum of 10 square metres of dedicated play space per child should be provided.
  - Play provision should be for all ages: under 5, 5-11, and 12+.
  - Where on-site provision is not possible or practical, the LPA should secure off-site provision or financial contributions.
  - Play space should be accessible, safe, stimulating, and located close to homes.

### GLA Shaping Neighbourhoods: Play and Informal Recreation SPG (2012)
- Sets out the Mayor's approach to implementing play space policy in London.
- **Child yield calculator**: Provides a methodology for calculating child yield based on dwelling size (number of bedrooms) and tenure (market, intermediate, social rented).
- **Play space hierarchy**:
  - **Doorstep play (under 5s)**: Immediately outside the home, within sight of the dwelling. Minimum 100 sqm. Within 100m walking distance.
  - **Local play (5-11 year olds)**: Within 100-400m walking distance. Minimum 300 sqm. Includes a range of play equipment and features.
  - **Neighbourhood play (12+ year olds)**: Within 400-800m walking distance. Minimum 500 sqm. Includes multi-use games areas (MUGAs), wheeled play, and youth shelters.
- **10 sqm per child benchmark**: Total play space provision should achieve a minimum of 10 sqm per child across all age groups.
- **Quality principles**: Play should be accessible, inclusive, stimulating, challenging, natural, and well-maintained.

### Fields in Trust (FIT) Guidance
- **Equipped/designated play areas**: 0.25 hectares per 1,000 population.
- **Play area classifications**:
  - **Local Area for Play (LAP)**: For children aged under 6. Minimum activity zone of 100 sqm. Within 100m walking distance (1 minute). No formal equipment required; designed for low-key games and social interaction.
  - **Locally Equipped Area for Play (LEAP)**: For children aged 4-8. Minimum activity zone of 400 sqm. Within 400m walking distance (5 minutes). Minimum 5 types of play equipment.
  - **Neighbourhood Equipped Area for Play (NEAP)**: For older children aged 8+. Minimum activity zone of 1,000 sqm. Within 1,000m walking distance (15 minutes). Minimum 8 types of play equipment plus a hard-surfaced area for ball games/wheeled play.
  - **Multi-Use Games Area (MUGA)**: Hard-surfaced, floodlit area for a variety of sports and informal recreation. Typically 40m x 20m minimum.
- Note: FIT updated its guidance in 2015 to move towards the above simplified hierarchy. Some local authorities still use the older NPFA/FIT Six-Acre Standard categories.

### Other Key Guidance
- **Local Plan Play Space Policies**: The relevant local plan will set out specific requirements for play space provision. These vary between authorities and must be referenced.
- **Local Play Strategy or Play Pitch Strategy**: Some authorities have adopted play strategies that set out detailed standards.
- **Design for Play: A Guide to Creating Successful Play Spaces (Play England, 2008)**: Best practice guide for play space design, endorsed by CABE.
- **Play Naturally (Natural England)**: Guidance on incorporating natural play elements.
- **Inclusive Play Design (Play England)**: Guidance on designing play spaces that are accessible and inclusive for children with disabilities.
- **BS EN 1176 and BS EN 1177**: European standards for playground equipment and impact-absorbing surfacing.
- **RoSPA (Royal Society for the Prevention of Accidents)**: Play safety guidance and inspection standards.
- **National Design Guide (2021)**: Well-designed places should include play spaces that are safe, attractive, and well-located.
- **Secured by Design**: Principles for reducing crime and anti-social behaviour in play areas through design.

## Section-by-Section Guidance

### 1. Introduction (250-500 words)
- State the purpose of the Play Space Assessment and the policy basis (NPPF Paragraphs 98-99; London Plan Policy S4 if in London).
- Identify the site by full postal address and site area in hectares.
- Summarise the proposed development: total number of dwellings, dwelling mix by bedroom size and tenure, and any non-residential elements.
- State the methodology: child yield calculation, catchment area analysis, quality assessment of existing provision, and proposed play strategy.
- State any limitations (e.g., reliance on published data, lack of local play strategy data).
- State the author's qualifications, or flag as "[PREPARED FOR REVIEW BY A QUALIFIED PLANNING CONSULTANT OR LANDSCAPE ARCHITECT]".

### 2. Policy Framework (300-600 words)
- Set out the national and local policy framework:
  - **NPPF Paragraphs 98-99**: Requirement for open space assessment and protection of existing play facilities.
  - **London Plan Policy S4** (if applicable): 10 sqm per child requirement, provision for all age groups, on-site preference.
  - **GLA Play SPG** (if applicable): Child yield calculator methodology, play space hierarchy (doorstep, local, neighbourhood), quality principles.
  - **Local Plan Policies**: Identify and quote the specific local plan policies relating to play space. These typically include quantitative standards (sqm per child or per dwelling), age group requirements, and design standards.
  - **Fields in Trust Standards**: Reference the FIT play area classifications (LAP, LEAP, NEAP) and benchmark standards.
  - **Other guidance**: Reference Design for Play, Inclusive Play Design, BS EN 1176/1177 as relevant.
- Conclude by stating which standards will be applied in the assessment.

### 3. Child Yield Calculation (300-500 words)
- Calculate the expected child population of the development:
  - **Dwelling mix**: List the proposed dwellings by bedroom size (studio, 1-bed, 2-bed, 3-bed, 4-bed+) and tenure (market, intermediate/shared ownership, social/affordable rent).
  - **Child yield multipliers**: Apply the local authority's adopted child yield rates. If in London, use the GLA child yield calculator from the Play SPG. If outside London, use the local authority's adopted rates or, if unavailable, the census-based child yield rates.
  - **Calculation by age group**: Calculate the expected number of children in each age group:
    - Under 5 years old.
    - 5-11 years old.
    - 12-17 years old (or 12+ depending on local categories).
  - **Total child yield**: Sum the age-group yields to give the total expected child population.
- Present the calculation in a clear table format showing dwelling type, number, tenure, child yield rate per age group, and total children per age group.
- Note that child yield rates vary significantly by tenure: social rented housing typically generates a higher child yield than market housing. This must be reflected in the calculation.
- If local child yield data is not available, flag as "[LOCAL CHILD YIELD MULTIPLIERS TO BE CONFIRMED WITH THE LPA]" and state the source of the rates used.

### 4. Existing Play Provision (300-600 words)
- Describe the existing play space provision within the relevant catchment area:
  - Identify all play areas within the FIT or local authority walking distance standards:
    - LAPs within 100m.
    - LEAPs within 400m.
    - NEAPs within 1,000m.
    - MUGAs within 1,000m.
  - For each existing play area, describe:
    - Name and location (with distance from the site boundary).
    - Type (LAP, LEAP, NEAP, MUGA, informal play space).
    - Target age group.
    - Size (square metres, if available).
    - Quality assessment: condition of equipment, surfacing, fencing, seating, accessibility, maintenance standard.
    - Any capacity constraints or deficiencies.
  - Assess the overall quality of existing provision against the local authority's play space quality standards (if published in the open space study or play strategy).
- Identify any gaps in provision by age group or by play area type.
- Include a plan or map showing the location of existing play facilities relative to the site.
- Where local data is not available, assess from aerial photography, Google Street View, and OS mapping, and flag as "[PLAY PROVISION SURVEY TO BE VERIFIED ON SITE]".

### 5. Proposed Play Strategy (400-700 words)
- Set out the proposed play strategy for the development:
  - **Total play space requirement**: Calculate the total play space quantum based on the child yield and the adopted standard (e.g., 10 sqm per child under London Plan Policy S4, or the local authority's standard). Show the calculation clearly.
  - **Play space by age group**: Break down the provision by age group to demonstrate that each age cohort is served:
    - **Under 5s (doorstep play)**: Describe the type and location of doorstep play within the development. Doorstep play should be within 100m of every dwelling containing family housing and within sight of the home. Typical features: sand play, low-level climbing, sensory planting, natural features, seating for carers.
    - **5-11 year olds (local play)**: Describe the equipped local play area(s) within the development. Should be within 400m of all dwellings. Minimum 5 types of equipment. Features: climbing structures, swings, slides, imaginative play, natural play features, seating.
    - **12+ year olds (neighbourhood play)**: Describe provision for older children and teenagers. May include MUGAs, wheeled play (skateboarding, BMX), outdoor gym equipment, social seating areas, or youth shelters. If on-site provision is not feasible for this age group, describe the off-site provision or financial contribution.
  - **On-site vs off-site**: Demonstrate that the maximum amount of play space is provided on-site. Where off-site provision or financial contributions are necessary, justify the approach and identify the specific off-site improvements to be made.
  - **Integration with open space**: Describe how the play spaces relate to the wider open space strategy, landscape design, and pedestrian/cycle movement network.
  - **Play value**: Describe how the play spaces will provide a range of play experiences: physical, social, creative, sensory, and nature-based. Reference Design for Play principles.
- Present the play space provision in a summary table showing: age group, number of children, standard applied, required area (sqm), proposed area (sqm), and surplus/deficit.

### 6. Play Space Design (400-700 words)
- Set out the design principles for the proposed play spaces:
  - **Inclusive design**: Demonstrate that play spaces are designed to be accessible and inclusive for children of all abilities, including wheelchair users and children with sensory impairments. Reference the Equality Act 2010 and Inclusive Play Design guidance. Include:
    - Wheelchair-accessible routes to and through the play area.
    - Accessible equipment (ground-level activities, wheelchair-accessible roundabouts, inclusive swings).
    - Sensory elements (sound, texture, colour, scent).
    - Seating for carers and parents with mobility impairments.
  - **Natural play**: Incorporate natural play elements following Play Naturally guidance:
    - Mounding and landform.
    - Log and boulder climbing.
    - Planting and den-building materials.
    - Water play (where appropriate and safe).
    - Wildlife habitats (bug hotels, bird boxes) as play features.
  - **Safety and standards**: Confirm compliance with BS EN 1176 (playground equipment safety) and BS EN 1177 (impact-absorbing surfacing). Note that RoSPA or an independent play safety inspector should review the detailed design.
  - **Natural surveillance**: Play areas should be overlooked by surrounding dwellings and/or pedestrian routes. At least two frontages of the play area should be overlooked.
  - **Boundary treatment**: Appropriate fencing where required (particularly for under 5s play near roads), but avoid excessive fencing that creates a hostile or institutional appearance.
  - **Landscaping**: Native and wildlife-friendly planting around play areas. Avoid poisonous plants (reference RHS list of potentially harmful plants). Provide shade through tree planting.
  - **Lighting**: Appropriate lighting for safety and extended use, designed sensitively to avoid light pollution and disturbance to wildlife and neighbouring residents.
  - **Anti-social behaviour mitigation**: Design measures following Secured by Design principles to reduce the risk of anti-social behaviour in and around play areas.
  - **Noise**: Consideration of noise from play areas on adjacent dwellings. Where play areas are adjacent to residential properties, consider acoustic barriers, buffer planting, or orientation of noisy equipment.

### 7. Management and Maintenance (200-400 words)
- Set out the management and maintenance arrangements:
  - **Management body**: Identify who will manage the play spaces: local authority adoption, management company, community trust, or residents' association.
  - **Inspection regime**: Describe the proposed inspection regime following RoSPA guidance:
    - Routine visual inspections: weekly.
    - Operational inspections: monthly to quarterly.
    - Annual main inspections: by a qualified play inspector (RPII registered).
  - **Maintenance standards**: Describe the maintenance regime for:
    - Equipment: repair, replacement, and painting/treatment.
    - Surfacing: top-up, repair, and replacement (wet pour, bark mulch, rubber mulch).
    - Landscaping: grass cutting, hedge maintenance, litter picking, graffiti removal.
    - Drainage: ensuring play areas drain freely and do not become waterlogged.
  - **Equipment replacement programme**: Set out the expected lifespan of equipment and the replacement programme (typically 15-25 years depending on material and type).
  - **Funding**: Describe the funding mechanism for ongoing maintenance (service charge, commuted sum, endowment).
  - **Section 106/planning conditions**: Reference any obligations or conditions securing the play provision and its maintenance.

### 8. Conclusion (150-300 words)
- Summarise the key findings:
  - The child yield of the development.
  - The quantum of play space required and provided.
  - How the play strategy addresses the needs of each age group.
  - The quality and accessibility of the proposed play provision.
  - The management and maintenance arrangements.
- Confirm compliance with:
  - NPPF Paragraphs 98-99.
  - London Plan Policy S4 (if applicable).
  - GLA Play SPG (if applicable).
  - Local plan play space policies (cite specific policy numbers).
  - Fields in Trust standards (where applied).
- Confirm that the proposed play provision is inclusive, age-appropriate, and designed to current best practice standards.
- Recommend any planning conditions or Section 106 obligations that should be attached to secure the play space provision and its long-term management.

## Quality Standards

- Reference specific NPPF paragraphs (98, 99, 100, 130) by number.
- Reference London Plan Policy S4 and the GLA Play SPG where the site is in London.
- Reference Fields in Trust guidance and play area classifications (LAP, LEAP, NEAP, MUGA) correctly.
- Use the correct child yield methodology for the local authority or, for London, the GLA child yield calculator.
- Present child yield calculations in clear tabular format broken down by dwelling type, tenure, and age group.
- Present play space calculations in clear tabular format showing requirement vs provision by age group.
- Reference Design for Play (Play England), Inclusive Play Design, and Play Naturally guidance.
- Reference BS EN 1176 and BS EN 1177 for safety compliance.
- Reference RoSPA inspection standards for management and maintenance.
- Clearly distinguish between doorstep play (under 5s), local play (5-11), and neighbourhood play (12+).
- Where local authority data has not been provided, clearly flag "[LOCAL PLAY SPACE DATA REQUIRED]" and state assumptions.
- Do not fabricate local authority child yield rates or play space standards. Use GLA or FIT standards as fallbacks and state clearly.
- Address inclusive design and the needs of children with disabilities.
- Address the play value and range of play experiences, not just the quantum of space.`;

export const PSA_SECTIONS: AssessmentSection[] = [
  {
    name: 'Introduction',
    description: 'Purpose, site identification, development description, methodology, and limitations.',
    required: true,
    min_words: 250,
    max_words: 500,
    guidance:
      'State the purpose of the PSA and the policy basis (NPPF Paragraphs 98-99; London Plan Policy S4 if applicable). Identify the site by address and area. Summarise the proposed development including dwelling numbers, mix by bedroom size and tenure. State the methodology and limitations.',
  },
  {
    name: 'Policy Framework',
    description: 'National and local planning policy framework for play space provision.',
    required: true,
    min_words: 300,
    max_words: 600,
    guidance:
      'Set out NPPF Paragraphs 98-99. Reference London Plan Policy S4 and GLA Play SPG if applicable. Identify specific local plan play space policies. Reference FIT play area classifications (LAP, LEAP, NEAP). Reference Design for Play and Inclusive Play Design guidance. State which standards will be applied.',
    subsections: [
      {
        name: 'National and Regional Policy',
        description: 'NPPF and London Plan (if applicable) play space policies.',
        required: true,
        min_words: 100,
        max_words: 250,
        guidance: 'Summarise NPPF Paragraphs 98-99 and London Plan Policy S4 (if in London). Reference GLA Play SPG.',
      },
      {
        name: 'Local Policy and Standards',
        description: 'Local plan policies and adopted standards for play space.',
        required: true,
        min_words: 150,
        max_words: 350,
        guidance: 'Identify specific local plan policies, quantitative standards, and design requirements for play space provision.',
      },
    ],
  },
  {
    name: 'Child Yield Calculation',
    description: 'Calculation of expected child population by age group based on dwelling mix and tenure.',
    required: true,
    min_words: 300,
    max_words: 500,
    guidance:
      'List dwellings by bedroom size and tenure. Apply local authority or GLA child yield multipliers. Calculate children by age group (under 5, 5-11, 12+). Present in a clear table. Note the higher child yield from affordable/social rented tenure. Flag if local data is unavailable.',
  },
  {
    name: 'Existing Play Provision',
    description: 'Assessment of existing play facilities within the catchment area.',
    required: true,
    min_words: 300,
    max_words: 600,
    guidance:
      'Identify all play areas within FIT or local walking distance standards. Describe each by name, location, distance, type, target age, size, quality, and capacity. Assess overall provision quality. Identify gaps by age group or facility type. Include a location plan if possible.',
    subsections: [
      {
        name: 'Existing Facilities Audit',
        description: 'Inventory of existing play facilities within the catchment.',
        required: true,
        min_words: 200,
        max_words: 400,
        guidance: 'Describe each existing play area: name, distance, type (LAP/LEAP/NEAP/MUGA), age group, size, condition, and accessibility.',
      },
      {
        name: 'Gaps in Provision',
        description: 'Identified deficiencies in existing play provision.',
        required: true,
        min_words: 75,
        max_words: 200,
        guidance: 'Identify gaps by age group, play area type, or quality. Assess whether existing provision has capacity for additional demand.',
      },
    ],
  },
  {
    name: 'Proposed Play Strategy',
    description: 'Strategy for meeting play space demand through on-site and off-site provision.',
    required: true,
    min_words: 400,
    max_words: 700,
    guidance:
      'Calculate total play space quantum (e.g., 10 sqm per child). Break down provision by age group: doorstep play (under 5s), local play (5-11), neighbourhood play (12+). Describe on-site provision. Justify any off-site contributions. Describe integration with open space and landscape. Present a summary table of requirement vs provision.',
    subsections: [
      {
        name: 'Play Space Quantum',
        description: 'Calculation of total play space requirement and proposed provision.',
        required: true,
        min_words: 100,
        max_words: 200,
        guidance: 'Calculate total play space needed based on child yield and standard (e.g., 10 sqm/child). State total proposed provision.',
      },
      {
        name: 'Provision by Age Group',
        description: 'Play provision for each age group: under 5s, 5-11, 12+.',
        required: true,
        min_words: 200,
        max_words: 400,
        guidance: 'Describe doorstep play (under 5s), local play (5-11), and neighbourhood play (12+). State location, size, features, and walking distances.',
      },
    ],
  },
  {
    name: 'Play Space Design',
    description: 'Design principles for the proposed play spaces.',
    required: true,
    min_words: 400,
    max_words: 700,
    guidance:
      'Address inclusive design (Equality Act 2010, wheelchair access, sensory elements). Describe natural play elements. Confirm compliance with BS EN 1176 and BS EN 1177. Address natural surveillance, boundary treatment, landscaping, lighting, noise, and anti-social behaviour mitigation through Secured by Design principles.',
    subsections: [
      {
        name: 'Inclusive and Accessible Design',
        description: 'Design for children of all abilities.',
        required: true,
        min_words: 100,
        max_words: 250,
        guidance: 'Describe wheelchair-accessible routes and equipment, sensory elements, and inclusive seating. Reference Equality Act 2010.',
      },
      {
        name: 'Play Value and Natural Play',
        description: 'Range of play experiences and natural play elements.',
        required: true,
        min_words: 100,
        max_words: 250,
        guidance: 'Describe range of play types (physical, social, creative, sensory, nature-based). Describe natural play features.',
      },
      {
        name: 'Safety, Surveillance, and Environment',
        description: 'Safety standards, overlooking, boundary treatment, and environmental considerations.',
        required: true,
        min_words: 100,
        max_words: 250,
        guidance: 'Address BS EN 1176/1177 compliance, natural surveillance, fencing, lighting, noise, and anti-social behaviour.',
      },
    ],
  },
  {
    name: 'Management and Maintenance',
    description: 'Long-term management and maintenance arrangements for play spaces.',
    required: true,
    min_words: 200,
    max_words: 400,
    guidance:
      'Identify the management body. Describe the RoSPA-compliant inspection regime (weekly, monthly, annual). Describe maintenance standards for equipment, surfacing, and landscaping. Set out the equipment replacement programme. Describe funding mechanisms. Reference Section 106 obligations.',
  },
  {
    name: 'Conclusion',
    description: 'Summary of findings and confirmation of policy compliance.',
    required: true,
    min_words: 150,
    max_words: 300,
    guidance:
      'Summarise child yield, play space requirement, proposed provision, design quality, and management arrangements. Confirm compliance with NPPF Paragraphs 98-99, London Plan Policy S4 (if applicable), GLA Play SPG (if applicable), local plan policies, and FIT standards. Recommend planning conditions or Section 106 obligations.',
  },
];

export const PSA_QUALITY: QualityCriteria = {
  min_policy_refs: 5,
  required_sections: [
    'Introduction',
    'Policy Framework',
    'Child Yield Calculation',
    'Existing Play Provision',
    'Proposed Play Strategy',
    'Play Space Design',
    'Management and Maintenance',
    'Conclusion',
  ],
  max_quality_score: 100,
};

export const PSA_TEMPLATE = {
  assessment_type: 'Play Space Assessment',
  short_name: 'PSA',
  version: 1,
  sections: PSA_SECTIONS,
  quality_criteria: PSA_QUALITY,
};
