import type { AssessmentSection, QualityCriteria } from '@/types';

/**
 * Social Infrastructure Assessment (SIA) -- required for major developments
 * generating significant new population to assess the impact on local
 * social infrastructure (schools, GPs, community facilities, emergency
 * services) and demonstrate adequate capacity or mitigation via S106/CIL.
 */

export const SIA_PROMPT = `You are preparing a Social Infrastructure Assessment (SIA) to accompany a planning application for a major development submitted to a local planning authority in England. The SIA should read as though prepared by a competent planning consultant or social infrastructure specialist with expertise in population yield estimation, capacity assessment, and planning obligation negotiation in the UK planning context.

## Document Purpose

A Social Infrastructure Assessment evaluates the impact of the proposed development's population on local social infrastructure provision and demonstrates that:
1. The additional population generated by the development can be accommodated within existing social infrastructure, or that appropriate mitigation is provided.
2. The assessment covers education (early years, primary, secondary, post-16, and SEN provision), healthcare (GP surgeries, dental practices, pharmacies), community facilities (libraries, community centres, places of worship, leisure centres), and emergency services (police, fire, ambulance).
3. Where capacity shortfalls are identified, appropriate mitigation is proposed through on-site provision, S106 financial contributions, or CIL.
4. The development accords with NPPF policies on community facilities and infrastructure provision.

## Key Policy and Guidance References

### National Planning Policy Framework (NPPF, December 2023)
- **Paragraph 93**: To provide the social, recreational and cultural facilities and services the community needs, planning policies and decisions should: plan positively for the provision and use of shared spaces, community facilities (such as local shops, meeting places, sports venues, open space, cultural buildings, public houses and places of worship) and other local services to enhance the sustainability of communities and residential environments; take into account and support the delivery of local strategies to improve health, social and cultural well-being for all sections of the community; guard against the unnecessary loss of valued facilities and services, particularly where this would reduce the community's ability to meet its day-to-day needs; ensure that established shops, facilities and services are able to develop and modernise, and are retained for the benefit of the community; and ensure an integrated approach to considering the location of housing, economic uses and community facilities and services.
- **Paragraph 94**: It is important that a sufficient choice of school places is available to meet the needs of existing and new communities. Local planning authorities should take a proactive, positive and collaborative approach to meeting this requirement, and to development that will widen choice in education. They should give great weight to the need to create, expand or alter schools and work with schools promoters, delivery bodies and statutory bodies to identify and resolve key planning issues before applications are submitted.
- **Paragraph 95**: Planning policies and decisions should promote public safety and take into account wider security and defence requirements.
- **Paragraph 34**: Developer contributions should only be sought where they meet all of the following tests: necessary to make the development acceptable in planning terms; directly related to the development; and fairly and reasonably related in scale and kind to the development.
- **Paragraph 55**: Local planning authorities should consider whether otherwise unacceptable development could be made acceptable through the use of conditions or planning obligations.
- **Paragraph 57**: Planning obligations must only be sought where they meet the tests in Regulation 122(2) of the CIL Regulations 2010 (as amended): necessary to make the development acceptable in planning terms; directly related to the development; and fairly and reasonably related in scale and kind to the development.

### Planning Practice Guidance (PPG)
- **Planning obligations**: Guidance on the use of S106 agreements to secure infrastructure provision and financial contributions.
- **Community Infrastructure Levy**: Guidance on CIL charging, spending, and the relationship between CIL and S106.
- **Housing and economic needs assessment**: Population and demographic projections.

### Department for Education (DfE) Guidance
- **DfE Pupil Yield and School Place Planning**: Guidance on estimating the number of school-age children generated by new housing developments, typically expressed as a pupil yield per dwelling by tenure and dwelling size.
- **Securing developer contributions for education (2019)**: DfE guidance on calculating education contributions, cost per pupil place, and the evidence required to justify contributions.
- Typical pupil yields (vary by authority and dwelling type):
  - Primary (4-11): 0.20-0.30 pupils per dwelling.
  - Secondary (11-16): 0.10-0.20 pupils per dwelling.
  - Post-16 (16-18): 0.02-0.05 pupils per dwelling.
  - Early years (0-4): 0.05-0.15 children per dwelling.
  - Note: yields vary significantly by dwelling size and tenure; affordable/social housing typically generates higher yields.

### NHS England / Integrated Care Board (ICB) Guidance
- **NHS England Healthy New Towns Programme**: Guidance on planning for healthcare in new development.
- **Integrated Care Board (ICB) / former CCG**: Local guidance on calculating healthcare contributions, GP capacity, and the cost of providing additional GP capacity (typically expressed as cost per patient place or cost per dwelling).
- Typical GP capacity standard: 1 GP per 1,800 patients (NHS England standard), though local ICBs may use different ratios.

### Other Key References
- **Infrastructure Delivery Plan (IDP)**: The local authority's assessment of infrastructure needs to support planned growth, including social infrastructure.
- **Local plan policies**: Social infrastructure policies, community facilities policies, planning obligations SPD.
- **Planning Obligations / Developer Contributions SPD**: Authority-specific guidance on the type and quantum of contributions required for social infrastructure.
- **CIL Charging Schedule**: Where the LPA has adopted CIL, the applicable rates and the infrastructure funded through CIL vs S106.
- **Schools Organisation Plan / School Place Planning Strategy**: Local authority's assessment of school place capacity and planned expansions.
- **Primary Care Strategy / Estates Strategy**: ICB's assessment of primary care capacity and planned investment.
- **GLA Social Infrastructure SPG (2015)**: For London boroughs, supplementary planning guidance on social infrastructure.

## Section-by-Section Guidance

### 1. Introduction (200-400 words)
- State the purpose of the Social Infrastructure Assessment and its policy basis (NPPF Paragraphs 93-95).
- Identify the site by location, local authority, and ward.
- Summarise the proposed development: number and mix of residential units (by number of bedrooms and tenure), anticipated population, and phasing.
- State the assessment methodology: population yield estimation, capacity assessment against published standards, identification of shortfalls, and mitigation proposals.
- Define the study area (typically a catchment radius appropriate to each infrastructure type: 800m-1.6km for primary schools, 3km for secondary schools, 800m-1km for GP surgeries).
- Note any pre-application discussions with the LPA, education authority, or ICB regarding infrastructure requirements.
- Outline the document structure.

### 2. Policy Framework (400-800 words)
- Set out NPPF Paragraphs 93-95, 34, 55, and 57 with a summary of community facilities, school places, and planning obligations requirements.
- Set out the PPG guidance on planning obligations and CIL.
- Set out the relevant local plan policies:
  - Social infrastructure / community facilities policies (requiring adequate provision and contributions for major development).
  - Education policies (safeguarding school sites, requiring contributions for school places).
  - Healthcare policies (requiring assessment of GP/healthcare capacity and contributions).
  - Open space, sport, and recreation policies (cross-reference with other assessments).
- Reference the Planning Obligations / Developer Contributions SPD:
  - List the types of infrastructure for which contributions are sought.
  - State the per-dwelling contribution rates where published (education, healthcare, community facilities, emergency services).
  - Note any formula or methodology specified for calculating contributions.
- Reference the CIL Charging Schedule (if adopted):
  - State the applicable CIL rate for the proposed development.
  - Identify which infrastructure types are funded through CIL (Regulation 123 list or Infrastructure Funding Statement) and which through S106.
- Reference the Infrastructure Delivery Plan and any identified infrastructure requirements for the area.
- Reference DfE guidance on securing developer contributions for education.
- Reference NHS/ICB guidance on healthcare contributions.

### 3. Methodology (300-500 words)
- Describe the methodology for the social infrastructure assessment:
  - **Population yield**: Explain the methodology for estimating the population generated by the development. State the source of yield ratios (local authority published data, DfE guidance, GLA Population Yield Calculator for London, or census-based estimates).
  - Present the yield ratios used:
    - Total population per dwelling (by dwelling size and tenure).
    - School-age children: primary (4-11), secondary (11-16), post-16 (16-18), early years (0-4).
    - GP-registering population.
  - **Capacity assessment**: Explain how existing capacity is assessed for each infrastructure type (published DfE data, school capacity returns, NHS data, council records).
  - **Surplus/deficit analysis**: Compare the additional demand generated by the development with the existing surplus capacity.
  - **Contribution calculation**: Where a shortfall is identified, calculate the required mitigation contribution using the LPA's published formulae or DfE/ICB standard costs.
- Note any data limitations and the sources used.

### 4. Population Yield (300-600 words)
- Present the estimated population yield from the proposed development:
  - **Total population**: State the total estimated population based on the proposed dwelling mix (by number of bedrooms) and tenure (market, affordable rent, shared ownership, social rent).
  - Present the calculation in a table:
    - Dwelling type (1-bed, 2-bed, 3-bed, 4+ bed) x number of dwellings x average household size = estimated population.
    - Split by tenure where yield ratios differ.
  - **School-age children**:
    - Early years (0-4): number of children.
    - Primary (4-11): number of pupils.
    - Secondary (11-16): number of pupils.
    - Post-16 (16-18): number of students.
    - SEN: estimated number requiring special provision (typically 2-3% of total pupil yield).
  - **Healthcare-registering population**: State the GP-registering population (typically 95-100% of total population).
  - Present the yield in a summary table.
  - State the source of the yield ratios and any local adjustments applied.
  - Where the dwelling mix has not been finalised, present a range or use a representative mix.

### 5. Education Assessment (500-1000 words)
- Assess the impact on education provision:
  - **Early years (0-4)**:
    - Estimate the number of early years places required.
    - Identify existing early years providers within the catchment (nurseries, pre-schools, childminders) and their capacity.
    - Assess the surplus/deficit of places.
    - Identify any planned early years provision.
  - **Primary schools (4-11)**:
    - Identify all primary schools within the catchment radius (typically 800m-1.6km or the appropriate walking distance).
    - For each school, state: name, capacity (Published Admission Number and total capacity), current roll (Number on Roll), and surplus/deficit of places.
    - Reference DfE school capacity data (SCAP returns) and the local authority's school place planning data.
    - Calculate the net impact: primary pupil yield minus available surplus capacity.
    - Identify any planned school expansions or new school provision.
  - **Secondary schools (11-16)**:
    - Identify all secondary schools within the catchment radius (typically 3km).
    - For each school, state: name, capacity, current roll, and surplus/deficit.
    - Calculate the net impact.
    - Identify planned expansions or new provision.
  - **Post-16 (16-18)**:
    - Brief assessment of sixth form and further education capacity.
  - **SEN provision**:
    - Estimate the SEN pupil yield (2-3% of total).
    - Assess local SEN school capacity.
  - Present the education capacity analysis in a summary table.
  - Where a shortfall is identified, calculate the education contribution:
    - State the DfE cost per pupil place (or locally adopted cost): typically the DfE new-build cost per pupil place published in the annual school building guidance.
    - Calculate: number of pupils requiring places x cost per place = total education contribution.
    - Split by phase (primary, secondary, post-16, SEN).
  - Where no shortfall exists, confirm that the development can be accommodated within existing and planned school capacity.

### 6. Healthcare Assessment (400-700 words)
- Assess the impact on primary healthcare provision:
  - **GP surgeries**:
    - Identify all GP practices within the catchment (typically 800m-1km or the local standard).
    - For each practice, state: name, registered patient list size, capacity, and whether accepting new patients.
    - Apply the standard GP ratio (1 GP per 1,800 patients, or the locally adopted standard).
    - Calculate the number of additional GP places required based on the development's population yield.
    - Assess the surplus/deficit of GP capacity within the catchment.
  - **Dental practices**:
    - Identify dental practices within the catchment.
    - Assess capacity (NHS vs private, accepting new patients).
  - **Pharmacies**:
    - Identify pharmacies within the catchment.
    - Assess capacity.
  - **Other healthcare**: Community health services, mental health services, hospital capacity (where relevant for very large developments).
  - Reference the ICB's assessment of healthcare capacity and any planned healthcare investment.
  - Where a shortfall is identified, calculate the healthcare contribution:
    - State the cost per patient place (or per dwelling rate) from the ICB or local SPD.
    - Calculate: additional patients x cost per patient = total healthcare contribution.
    - Alternatively: number of dwellings x per-dwelling contribution rate.
  - If on-site healthcare provision is proposed (e.g., a new GP surgery shell), describe the provision and the handover arrangements.

### 7. Community Facilities (300-600 words)
- Assess the impact on community facilities:
  - **Libraries**: Identify the nearest public library and its capacity. Assess whether the additional population can be accommodated or whether a contribution towards library services is required.
  - **Community centres / halls**: Identify existing community meeting spaces. Assess capacity and suitability. Note any on-site community space provision within the development.
  - **Places of worship**: Identify places of worship for the anticipated demographic mix. Note any on-site provision (typically only for very large developments).
  - **Leisure centres / sports facilities**: Identify the nearest leisure centre and sports facilities. Assess capacity. Cross-reference with the open space and recreation assessment.
  - **Youth facilities**: Identify youth clubs, adventure playgrounds, and other youth provision.
  - **Social care**: Where relevant, assess the impact on adult social care and children's services.
- Reference the local authority's standards for community facility provision (typically expressed as floorspace per 1,000 population or per dwelling).
- Where contributions are required, state the per-dwelling rate from the SPD or calculate using the standard formula.
- If on-site community facilities are proposed, describe the provision (floorspace, use, management arrangements, and delivery timing).

### 8. Emergency Services (200-400 words)
- Assess the impact on emergency services:
  - **Police (Metropolitan/County police force)**:
    - Identify the nearest police station or neighbourhood policing base.
    - Assess whether the additional population generates a need for enhanced policing capacity.
    - State any policing contribution sought by the police authority (typically set out in the SPD or via consultation response).
  - **Fire and rescue service**:
    - Identify the nearest fire station and its response time to the development site.
    - Assess whether the development affects fire service response times or requires additional capacity.
    - Note any fire safety requirements (cross-reference with the Fire Statement where prepared).
  - **Ambulance service (London Ambulance Service / regional ambulance trust)**:
    - Identify the nearest ambulance station.
    - Assess whether the additional population generates a need for additional ambulance capacity.
  - Note any emergency service contributions set out in the SPD.
  - Note any on-site provisions for emergency services (e.g., secure-by-design measures, fire hydrants, ambulance access).

### 9. Other Social Infrastructure (200-400 words)
- Assess any other social infrastructure relevant to the proposed development:
  - **Burial space / cemeteries**: Where locally identified as a need, assess capacity and contribution requirements.
  - **Allotments and community growing spaces**: Assess provision against local plan standards. Note any on-site allotment provision.
  - **Public toilets**: Where relevant (e.g., town centre developments).
  - **Post offices, banks, and other services**: Note accessibility to essential services.
- This section may be brief where other infrastructure types are not relevant to the proposed development. State this explicitly.

### 10. Mitigation and Contributions (400-800 words)
- Present a summary of all identified social infrastructure impacts and proposed mitigation:
  - Present in a table:
    - Infrastructure type.
    - Demand generated by the development (number of places/patients/users).
    - Existing surplus capacity.
    - Net deficit (if any).
    - Proposed mitigation (on-site provision or financial contribution).
    - Amount of financial contribution (£).
    - Mechanism (S106 or CIL).
  - For each contribution, confirm that it meets the three S106 tests (NPPF Paragraph 57 / CIL Regulation 122(2)):
    - Necessary to make the development acceptable in planning terms.
    - Directly related to the development.
    - Fairly and reasonably related in scale and kind.
  - Note the relationship between S106 and CIL: where infrastructure is funded through CIL (listed in the Infrastructure Funding Statement), it should not also be the subject of a S106 obligation (to avoid double-counting under CIL Regulation 123).
  - Present the total S106 obligation for social infrastructure.
  - Describe any triggers for payment (e.g., prior to commencement, on occupation of the Xth dwelling, phased payments).
  - Describe any on-site provision (community facility, healthcare shell, school site safeguarding) and the delivery mechanism (condition, S106 obligation).

### 11. Conclusion (300-500 words)
- Summarise the proposed development's population yield and the impact on each category of social infrastructure.
- Confirm that the development can be satisfactorily accommodated within existing and planned social infrastructure, with the proposed mitigation measures.
- Present the headline contribution figures:
  - Education: total contribution or confirmation of capacity.
  - Healthcare: total contribution or confirmation of capacity.
  - Community facilities: total contribution or on-site provision.
  - Emergency services: any contributions.
  - Total S106 social infrastructure obligation.
- Confirm compliance with NPPF Paragraphs 93-95, 34, 55, and 57.
- Confirm compliance with the local plan social infrastructure policies and SPD.
- Confirm that all contributions meet the three S106 tests.
- Conclude that the development will not result in unacceptable pressure on social infrastructure and that the proposed mitigation is appropriate and proportionate.
- Note any further consultation with the education authority, ICB, or community groups recommended.

## Quality Standards

- Reference NPPF Paragraphs 93-95, 34, 55, and 57 by specific number.
- Reference the DfE guidance on securing developer contributions for education.
- Reference the ICB or NHS England guidance on healthcare contributions.
- Use locally published pupil yield ratios (or DfE standard ratios where local data is unavailable).
- Present capacity data for specific schools and GP practices within the catchment (using DfE SCAP data, NHS data, or local authority monitoring).
- Calculate contributions using locally adopted cost-per-place or per-dwelling rates.
- Confirm compliance with the three S106 tests (CIL Regulation 122(2)).
- Address the S106/CIL overlap and avoid double-counting.
- Present data in tables (population yield, school capacity, GP capacity, contributions summary).
- Where specific capacity data has not been obtained, flag as "[CAPACITY DATA TO BE OBTAINED FROM [EDUCATION AUTHORITY / ICB / LPA]]".
- Do not fabricate school rolls, GP list sizes, or capacity figures.
- Professional planning language throughout.`;

export const SIA_SECTIONS: AssessmentSection[] = [
  {
    name: 'Introduction',
    description: 'Purpose, site, development summary, methodology, study area, and pre-application discussions.',
    required: true,
    min_words: 200,
    max_words: 400,
    guidance:
      'State the SIA purpose and NPPF basis (Paragraphs 93-95). Identify the site and local authority. Summarise the development (dwelling mix, tenure, population, phasing). State the methodology. Define catchment areas. Note pre-application discussions. Outline the document structure.',
  },
  {
    name: 'Policy Framework',
    description: 'NPPF, PPG, local plan social infrastructure policies, SPD contribution rates, CIL, and IDP.',
    required: true,
    min_words: 400,
    max_words: 800,
    guidance:
      'Set out NPPF Paragraphs 93-95, 34, 55, 57. Reference PPG on planning obligations and CIL. Set out local plan policies on social infrastructure, education, and healthcare. Reference the SPD contribution rates. Reference the CIL Charging Schedule and Infrastructure Funding Statement. Reference the IDP. Reference DfE and ICB guidance.',
  },
  {
    name: 'Methodology',
    description: 'Population yield estimation, capacity assessment, surplus/deficit analysis, and contribution calculation.',
    required: true,
    min_words: 300,
    max_words: 500,
    guidance:
      'Explain population yield methodology and source of ratios. Present yield ratios by dwelling type and tenure. Explain capacity assessment approach for each infrastructure type. Explain contribution calculation methodology. Note data sources and limitations.',
  },
  {
    name: 'Population Yield',
    description: 'Estimated total population, school-age children by phase, and healthcare-registering population.',
    required: true,
    min_words: 300,
    max_words: 600,
    guidance:
      'Present dwelling mix table (bedrooms x tenure x number). Calculate total population. Calculate school-age children: early years (0-4), primary (4-11), secondary (11-16), post-16, SEN. Calculate healthcare-registering population. Present in summary tables. State yield ratio sources.',
  },
  {
    name: 'Education Assessment',
    description: 'Early years, primary, secondary, post-16, and SEN capacity assessment and contribution calculation.',
    required: true,
    min_words: 500,
    max_words: 1000,
    guidance:
      'For each phase: identify schools in catchment, state capacity and roll, calculate surplus/deficit, assess net impact. Present in tables. Calculate education contributions using DfE cost per place. Address planned expansions and new school provision. Address SEN.',
    subsections: [
      {
        name: 'Primary Education',
        description: 'Primary schools within catchment: capacity, roll, surplus, and contribution.',
        required: true,
        min_words: 150,
        max_words: 400,
        guidance: 'Identify primary schools (800m-1.6km). State capacity, roll, surplus/deficit for each. Calculate net impact. Calculate contribution if deficit.',
      },
      {
        name: 'Secondary Education',
        description: 'Secondary schools within catchment: capacity, roll, surplus, and contribution.',
        required: true,
        min_words: 150,
        max_words: 400,
        guidance: 'Identify secondary schools (3km). State capacity, roll, surplus/deficit for each. Calculate net impact. Calculate contribution if deficit.',
      },
      {
        name: 'Early Years, Post-16, and SEN',
        description: 'Early years providers, post-16 capacity, and special educational needs provision.',
        required: true,
        min_words: 100,
        max_words: 250,
        guidance: 'Assess early years capacity. Brief assessment of post-16 and FE. Estimate SEN yield (2-3%) and assess provision.',
      },
    ],
  },
  {
    name: 'Healthcare Assessment',
    description: 'GP surgeries, dental practices, pharmacies: capacity, patient lists, and contribution calculation.',
    required: true,
    min_words: 400,
    max_words: 700,
    guidance:
      'Identify GP practices in catchment. State list size, capacity, and acceptance status. Calculate additional GP demand. Assess surplus/deficit. Assess dental and pharmacy capacity. Calculate healthcare contribution using ICB rates. Describe any on-site healthcare provision.',
  },
  {
    name: 'Community Facilities',
    description: 'Libraries, community centres, leisure, places of worship, youth facilities.',
    required: true,
    min_words: 300,
    max_words: 600,
    guidance:
      'Identify and assess capacity of libraries, community centres, leisure centres, and other facilities. Reference local standards for provision. Calculate contributions where required. Describe any on-site community facility provision.',
  },
  {
    name: 'Emergency Services',
    description: 'Police, fire, and ambulance capacity and contributions.',
    required: true,
    min_words: 200,
    max_words: 400,
    guidance:
      'Assess police, fire, and ambulance capacity. State nearest stations and response times. Note any contributions sought by emergency services. Note on-site provisions (Secured by Design, fire hydrants, access).',
  },
  {
    name: 'Other Social Infrastructure',
    description: 'Burial space, allotments, public toilets, and other services.',
    required: true,
    min_words: 200,
    max_words: 400,
    guidance:
      'Assess any other relevant social infrastructure: burial space, allotments, post offices, banks. State if not relevant. Note any on-site provision.',
  },
  {
    name: 'Mitigation and Contributions',
    description: 'Summary table of impacts, mitigation, contributions, S106 tests, and CIL/S106 relationship.',
    required: true,
    min_words: 400,
    max_words: 800,
    guidance:
      'Present summary table: infrastructure type, demand, surplus, deficit, mitigation, contribution amount, mechanism (S106/CIL). Confirm S106 tests met for each. Address S106/CIL overlap. State total S106 obligation. Describe triggers and phasing. Describe on-site provision delivery.',
  },
  {
    name: 'Conclusion',
    description: 'Headline contributions, capacity confirmation, policy compliance, and overall acceptability.',
    required: true,
    min_words: 300,
    max_words: 500,
    guidance:
      'Summarise population yield and impact on each infrastructure category. Present headline contributions (education, healthcare, community, emergency services, total). Confirm NPPF and local plan compliance. Confirm S106 tests. Conclude that infrastructure impacts are acceptable with proposed mitigation.',
  },
];

export const SIA_QUALITY: QualityCriteria = {
  min_policy_refs: 6,
  required_sections: [
    'Introduction',
    'Policy Framework',
    'Methodology',
    'Population Yield',
    'Education Assessment',
    'Healthcare Assessment',
    'Community Facilities',
    'Emergency Services',
    'Other Social Infrastructure',
    'Mitigation and Contributions',
    'Conclusion',
  ],
  max_quality_score: 100,
};

export const SIA_TEMPLATE = {
  assessment_type: 'Social Infrastructure Assessment',
  short_name: 'SIA',
  version: 1,
  sections: SIA_SECTIONS,
  quality_criteria: SIA_QUALITY,
};
