import type { AssessmentSection, QualityCriteria } from '@/types';

/**
 * Ventilation / Extraction Statement (VES) -- demonstrates that the
 * proposed ventilation or extraction system (typically for commercial
 * kitchens, restaurants, takeaways, or industrial processes) will not
 * cause unacceptable odour, noise, or visual amenity impacts on
 * neighbouring properties.
 *
 * Required by most local planning authorities for A3/A4/A5 (now E/Sui
 * Generis) food and drink uses, and for other uses involving
 * mechanical ventilation or extraction that may affect amenity.
 *
 * AI Difficulty: Easy | Typical length: 5-15 pages
 */

export const VES_PROMPT = `You are preparing a Ventilation / Extraction Statement to accompany a planning application in England. The statement demonstrates that the proposed mechanical ventilation and/or extraction system will operate without causing unacceptable impacts on the amenity of neighbouring properties from odour, noise, fumes, or visual intrusion.

## Document Purpose

The Ventilation / Extraction Statement must:
- Describe the proposed ventilation and/or extraction system in sufficient technical detail for the planning authority to assess its adequacy.
- Demonstrate that the system will effectively control and disperse cooking odours, fumes, and grease to prevent nuisance to neighbouring occupiers.
- Demonstrate that the noise generated by the ventilation/extraction equipment will not cause unacceptable disturbance to neighbouring properties.
- Describe the discharge location and demonstrate adequate dispersal of extracted air.
- Address the visual impact of any external plant, ductwork, or flues on the streetscene and neighbouring amenity.
- Set out the maintenance regime to ensure the system continues to perform effectively over time.
- Provide confidence to the local planning authority that the development will not give rise to statutory nuisance complaints.

## Key Policy and Legislation References

### National Planning Policy Framework (NPPF, December 2023)
- **Paragraph 130**: Planning policies and decisions should ensure that developments create places with a high standard of amenity for existing and future users.
- **Paragraph 180**: Planning policies and decisions should contribute to and enhance the natural and local environment by preventing new development from contributing to, or being put at unacceptable risk from, or being adversely affected by, unacceptable levels of air, noise, or other pollution.
- **Paragraph 191**: Planning policies and decisions should ensure that new development is appropriate for its location taking into account the likely effects (including cumulative effects) of pollution on health, living conditions, and the natural environment, as well as the potential sensitivity of the site or wider area to impacts that could arise from the development.
- **Paragraph 192**: Planning policies and decisions should ensure that new development can be integrated effectively with existing businesses and community facilities. Existing businesses and facilities should not have unreasonable restrictions placed on them as a result of development permitted after they were established.

### Environmental Protection Act 1990
- **Part III**: Statutory nuisance provisions. Section 79(1) defines statutory nuisances including:
  - (a) premises in such a state as to be prejudicial to health or a nuisance.
  - (d) any dust, steam, smell, or other effluvia arising on industrial, trade, or business premises and being prejudicial to health or a nuisance.
  - (g) noise emitted from premises so as to be prejudicial to health or a nuisance.
  - (ga) noise that is prejudicial to health or a nuisance and is emitted from or caused by a vehicle, machinery, or equipment in a street.
- The VES should demonstrate that the proposed system will prevent the creation of statutory nuisance from odour and noise.

### Defra Guidance on the Control of Odour and Noise from Commercial Kitchen Exhaust Systems (2005)
- Provides guidance on the assessment and control of odour and noise from commercial kitchen ventilation systems.
- Classifies cooking types by odour potential (low, medium, high).
- Sets out the required levels of odour control based on proximity to sensitive receptors and cooking type.
- Recommends a hierarchy of odour control measures: filtration, carbon adsorption, electrostatic precipitation (ESP), UV ozone treatment.
- Provides guidance on discharge stack heights and locations for adequate dispersal.
- This is the primary technical reference for commercial kitchen ventilation assessments.

### EMAQ+ Guidance on the Assessment of Odour (2014, updated 2018)
- Provides guidance on assessing odour impacts from various sources, including commercial kitchens.
- Sets out the "FIDOL" factors for assessing odour: Frequency, Intensity, Duration, Offensiveness, Location.
- Provides exposure criteria and assessment methodologies.

### Building Regulations Approved Document F: Ventilation (2021)
- Sets out the minimum ventilation requirements for buildings.
- **Volume 1**: Dwellings — relevant where the development includes residential uses above or adjacent to commercial uses with extraction.
- **Volume 2**: Buildings other than dwellings — relevant for the commercial use itself.
- Requirements for extract ventilation rates, kitchen ventilation, and background ventilation.
- While Building Regulations compliance is not a planning matter, the VES should demonstrate that the proposed system is consistent with achieving AD F compliance.

### BS 6173:2001 Installation and Maintenance of Gas-Fired Catering Appliances (Withdrawn, but referenced)
- Previously provided guidance on ventilation requirements for gas-fired catering equipment.
- Now superseded by updated standards but historically referenced in kitchen ventilation assessments.

### DW/172 (BESA) Specification for Kitchen Ventilation Systems (2018)
- Published by the Building Engineering Services Association (BESA, formerly HVCA).
- Provides detailed specification for commercial kitchen ventilation systems, including canopy design, ductwork, extract rates, filtration, and fire safety.
- Sets out minimum extract air velocities and capture velocities for different cooking equipment.
- The primary industry standard for commercial kitchen ventilation design.

### CIBSE Guide B: Heating, Ventilating, Air Conditioning and Refrigeration
- Provides design guidance for ventilation systems, including commercial kitchen ventilation.
- Includes guidance on external noise from mechanical plant (Section B4: Noise and Vibration Control).

### BS 4142:2014+A1:2019 Methods for Rating and Assessing Industrial and Commercial Sound
- The standard methodology for assessing noise from industrial and commercial operations (including mechanical plant) at noise-sensitive receptors.
- Requires comparison of the "rating level" of the noise source with the "background sound level" at the receptor.
- A difference of +5 dB or more (rating level above background) is likely to be an indication of adverse impact; +10 dB or more is likely to be an indication of significant adverse impact.
- The VES should include a BS 4142 assessment of noise from the ventilation/extraction equipment.

### Local Plan Policies
- Most local plans contain policies on amenity, pollution control, and the protection of residential amenity from commercial uses.
- Some local authorities have specific supplementary planning guidance or development management policies for food and drink uses, requiring ventilation/extraction details.
- Reference the specific local plan policies applicable to the development site.

### Other Key References
- World Health Organization Guidelines for Community Noise.
- Institute of Acoustics Good Practice Guide on the Control of Noise from Pubs and Clubs.
- Gas Safe Register guidance on commercial catering installations.
- Clean Air Act 1993 (relevant where combustion products are discharged).
- Anti-social Behaviour Act 2003 (noise nuisance provisions).

## Section-by-Section Guidance

### 1. Introduction (150-300 words)
- State the purpose of the Ventilation / Extraction Statement and why it has been prepared.
- Identify the application site: address, location, and context (including proximity to residential properties and other sensitive receptors).
- Describe the proposed use: type of food/drink establishment (restaurant, takeaway, cafe, bakery, pub, or other use), seating capacity, kitchen size, and types of cooking proposed.
- Describe the operating hours (proposed opening times and kitchen operating times, including any early morning or late night operation).
- Identify the sensitive receptors: residential properties above, adjacent to, or near the premises (specify distances and relationship — e.g., flats above, terraced houses to the rear, residential use across the street).
- State whether the ventilation/extraction system design has been prepared by a specialist ventilation engineer.
- Outline the document structure.

### 2. Policy Framework (250-400 words)
- Set out the relevant national policy context, referencing the NPPF paragraphs listed above (130, 180, 191, 192).
- Reference the Environmental Protection Act 1990 Part III (statutory nuisance) and the relevance of preventing odour and noise nuisance.
- Reference the Defra guidance on commercial kitchen exhaust systems (2005) as the primary technical standard.
- Reference EMAQ+ guidance on odour assessment.
- Reference BS 4142:2014+A1:2019 for noise assessment methodology.
- Reference DW/172 (BESA) for kitchen ventilation system design.
- Reference Building Regulations Approved Document F (noting it is a Building Regulations matter but relevant context).
- Reference applicable local plan policies on amenity, food and drink uses, and pollution control.
- Reference any supplementary planning guidance from the local authority on ventilation/extraction.

### 3. Proposed Ventilation/Extraction System (400-700 words)
- Describe the proposed ventilation/extraction system in technical detail:
  - **Kitchen canopy**: Type (wall-mounted, island), dimensions, capture velocity, position relative to cooking equipment.
  - **Extraction rate**: Calculated extract air volume flow rate (litres/second or m3/hour) based on the cooking equipment installed, canopy size, and DW/172 methodology.
  - **Ductwork**: Material (galvanised steel), diameter/dimensions, route from canopy to discharge point, fire rating, access for cleaning and inspection.
  - **Fan**: Type (centrifugal, axial), capacity, pressure, speed control, vibration isolation (anti-vibration mounts, flexible connections).
  - **Odour control equipment**:
    - Grease filtration: baffle filters, mesh filters, automatic wash-down systems.
    - Primary filtration: electrostatic precipitator (ESP) for particulate and grease removal.
    - Carbon filtration: activated carbon filters for odour removal.
    - UV ozone treatment: UV-C lamps for breaking down odour molecules.
    - State the combination of treatments proposed and justify against the Defra guidance risk assessment (cooking type vs proximity to receptors).
  - **Make-up air**: Supply air system to replace extracted air, preventing negative pressure in the kitchen. Source of supply air and any heating/tempering.
  - **Controls**: Speed control, interlocking with cooking equipment, timer operation, maintenance indicators.
- Classify the cooking type by odour potential using the Defra guidance categories:
  - Low: reheating pre-cooked food, light snacks.
  - Medium: standard restaurant cooking (grills, ovens, fryers — moderate volumes).
  - High: heavy frying, chargrilling, tandoori, wok cooking, fish and chips.
- Justify the level of odour control provided based on the cooking type and proximity to receptors.

### 4. Odour and Noise Impact (400-700 words)
#### 4.1 Odour Assessment
- Assess the odour risk using the Defra guidance framework:
  - Cooking type and odour potential (low/medium/high).
  - Proximity and sensitivity of receptors.
  - Resultant odour control requirement (low/medium/high).
- Describe how the proposed odour control measures (filtration, ESP, carbon, UV) achieve the required level of control.
- Assess the residual odour impact after treatment: confirm that the system will reduce odour emissions to a level that will not cause nuisance at the nearest sensitive receptor.
- Address any cumulative effects (if other food/drink uses are present in the vicinity).
- Reference the EMAQ+ FIDOL factors where applicable.

#### 4.2 Noise Assessment
- Assess the noise impact of the ventilation/extraction equipment using BS 4142:2014+A1:2019 methodology:
  - **Source noise levels**: State the sound power level (Lw) or sound pressure level (Lp) of the fan and any other equipment at 1 metre. Provide manufacturer's data or estimated levels.
  - **Propagation**: Calculate the noise level at the nearest noise-sensitive receptor, accounting for distance attenuation, screening, reflection, and any ductwork attenuation or silencer.
  - **Rating level**: Apply any character corrections (tonality, impulsivity, intermittency, other distinctive features) to arrive at the rating level.
  - **Background sound level**: State the measured or estimated background sound level (LA90) at the receptor location. If measurements have not been taken, state the basis for the assumed background level and flag that a survey may be required.
  - **Assessment**: Compare the rating level with the background sound level. The difference determines the likely impact significance per BS 4142.
- Describe noise mitigation measures incorporated:
  - Attenuators/silencers in ductwork (in-duct attenuators, splitter silencers).
  - Acoustic enclosure for external plant.
  - Anti-vibration mounts for fans and motors.
  - Flexible connections to prevent structure-borne noise transmission.
  - Time-limited operation (not operating during night-time hours where feasible).
- State the target noise criterion: the rating level should not exceed the background sound level at the nearest noise-sensitive receptor (i.e., a BS 4142 difference of 0 dB or less).

### 5. Discharge Location and Dispersal (300-500 words)
- Describe the discharge point (flue/stack terminal):
  - Location on the building (rear, side, roof-mounted).
  - Height above adjacent roof level and nearest openable windows.
  - Distance from the nearest sensitive receptor (horizontal and vertical).
  - Discharge velocity and direction (vertical discharge preferred for maximum dispersal).
- Demonstrate that the discharge location achieves adequate dispersal:
  - Stack height: minimum 1 metre above the ridge of any roof within a specified radius (Defra guidance recommends discharge at least 1 metre above the ridge of any building within the same block or immediately adjacent).
  - Avoid recirculation: the discharge point should be located to avoid entrainment of extracted air into any air intakes, openable windows, or outdoor amenity areas.
  - Efflux velocity: recommended minimum 15 m/s for adequate dispersal and to resist wind effects.
- Address the visual impact of any external flue, ductwork, or plant:
  - Material and finish of external flues (colour-matched to building, stainless steel, painted).
  - Screening of roof-mounted equipment from public views.
  - Impact on the streetscene and any heritage or conservation area considerations.
  - If the building is listed or in a conservation area, address heritage impacts of external plant and any Listed Building Consent or conservation area requirements.

### 6. Maintenance Arrangements (200-400 words)
- Set out the maintenance regime for the ventilation/extraction system:
  - **Grease filters**: Cleaning frequency (daily or weekly as appropriate).
  - **Ductwork**: Internal cleaning frequency (minimum every 6-12 months, more frequently for heavy use). Reference TR/19 (BESA Guide to Good Practice: Internal Cleanliness of Ventilation Systems).
  - **ESP / carbon filters / UV lamps**: Replacement and servicing schedules (ESP cleaning monthly, carbon filter replacement every 3-6 months, UV lamp replacement annually).
  - **Fan**: Annual servicing, belt replacement, bearing lubrication, vibration checks.
  - **Fire dampers**: Annual inspection and testing.
- Describe the maintenance record-keeping system and how records will be available for inspection by the local authority.
- Identify who will be responsible for maintenance (operator, facilities management company, specialist ventilation maintenance contractor).
- Address the consequences of poor maintenance (reduced odour control, increased noise, fire risk) and the commitment to maintaining the system in good working order.
- State any anticipated planning conditions requiring a maintenance plan and/or maintenance records.

### 7. Conclusion (150-300 words)
- Summarise the proposed ventilation/extraction system and its key features.
- Confirm that the system has been designed to control cooking odours to a level that will not cause nuisance to neighbouring occupiers, based on the Defra guidance framework.
- Confirm that the noise from the ventilation/extraction equipment will comply with BS 4142:2014+A1:2019, with the rating level not exceeding the background sound level at the nearest receptor.
- Confirm that the discharge location achieves adequate dispersal and complies with Defra guidance on stack heights.
- Confirm that the system has been designed in accordance with DW/172 (BESA).
- Confirm that a maintenance regime will be implemented to maintain the system's performance.
- Confirm compliance with national and local planning policies on amenity and pollution.
- State any recommended planning conditions (e.g., installation before first use, maintenance plan submission, hours of operation restriction, noise limit condition).
- Note that detailed design and installation will be undertaken by specialist ventilation engineers and will comply with Building Regulations Approved Document F.

## Quality Standards

- Reference the NPPF and specific amenity paragraphs (130, 180, 191, 192).
- Reference the Environmental Protection Act 1990 Part III (statutory nuisance).
- Reference the Defra guidance on commercial kitchen exhaust systems (2005) in detail.
- Reference BS 4142:2014+A1:2019 for noise assessment methodology.
- Reference DW/172 (BESA) for kitchen ventilation system design.
- Include technical specification of the ventilation system (extraction rate, fan specification, odour control equipment).
- Classify the cooking type by odour potential and justify the level of odour control provided.
- Include a noise assessment comparing the rating level with the background sound level at the nearest receptor.
- Describe the discharge location and demonstrate adequate stack height and dispersal.
- Address the visual impact of external plant and ductwork.
- Set out a maintenance regime with specific frequencies and responsibilities.
- Address both odour and noise impacts — both are essential components.
- Use correct ventilation and acoustics terminology: extract rate, capture velocity, electrostatic precipitator, activated carbon, rating level, background sound level, character correction.
- Professional language appropriate for planning officers and environmental health officers.`;

export const VES_SECTIONS: AssessmentSection[] = [
  {
    name: 'Introduction',
    description: 'Purpose, site context, proposed use, operating hours, and sensitive receptors.',
    required: true,
    min_words: 150,
    max_words: 300,
    guidance:
      'State the purpose of the VES. Identify the site and proximity to sensitive receptors. Describe the proposed use, kitchen type, and cooking methods. State operating hours. Confirm specialist input. Outline document structure.',
  },
  {
    name: 'Policy Framework',
    description: 'NPPF amenity policies, Environmental Protection Act, Defra guidance, BS 4142, and local policies.',
    required: true,
    min_words: 250,
    max_words: 400,
    guidance:
      'Reference NPPF paragraphs 130, 180, 191, 192. Reference EPA 1990 Part III. Reference Defra guidance on commercial kitchen exhaust (2005). Reference EMAQ+ and BS 4142. Reference DW/172 and AD F. Reference local plan policies.',
  },
  {
    name: 'Proposed Ventilation/Extraction System',
    description: 'Canopy, extraction rate, ductwork, fan, odour control equipment, make-up air, and controls.',
    required: true,
    min_words: 400,
    max_words: 700,
    guidance:
      'Describe kitchen canopy and extract rate calculation. Describe ductwork route and specification. Describe fan and vibration isolation. Describe odour control hierarchy (filtration, ESP, carbon, UV). Classify cooking type by Defra categories. Justify odour control level. Describe make-up air and controls.',
  },
  {
    name: 'Odour and Noise Impact',
    description: 'Odour risk assessment per Defra guidance and noise assessment per BS 4142.',
    required: true,
    min_words: 400,
    max_words: 700,
    guidance:
      'Assess odour risk using Defra framework (cooking type, proximity, control required). Confirm residual odour will not cause nuisance. Assess noise using BS 4142 (source level, propagation, rating level vs background). Describe noise mitigation measures. State target criterion.',
    subsections: [
      {
        name: 'Odour Assessment',
        description: 'Defra risk assessment, control measures, and residual impact.',
        required: true,
        min_words: 200,
        max_words: 350,
        guidance: 'Classify cooking type. Assess proximity to receptors. State odour control requirement. Confirm system achieves required level. Address cumulative effects.',
      },
      {
        name: 'Noise Assessment',
        description: 'BS 4142 assessment of fan noise at nearest sensitive receptor.',
        required: true,
        min_words: 200,
        max_words: 400,
        guidance: 'State source noise levels. Calculate level at receptor. Apply character corrections. Compare rating level with background. Describe mitigation. State target criterion.',
      },
    ],
  },
  {
    name: 'Discharge Location and Dispersal',
    description: 'Flue/stack location, height, velocity, dispersal adequacy, and visual impact.',
    required: true,
    min_words: 300,
    max_words: 500,
    guidance:
      'Describe discharge point location and height. Demonstrate adequate stack height per Defra guidance. State efflux velocity. Address recirculation avoidance. Describe visual appearance and impact on streetscene. Address heritage or conservation area considerations.',
  },
  {
    name: 'Maintenance Arrangements',
    description: 'Cleaning and servicing schedules, record keeping, and responsibilities.',
    required: true,
    min_words: 200,
    max_words: 400,
    guidance:
      'Set out cleaning/servicing frequencies for filters, ductwork, ESP, carbon, UV, fan. Reference TR/19. Describe record keeping. State maintenance responsibilities. Address consequences of poor maintenance. State anticipated conditions.',
  },
  {
    name: 'Conclusion',
    description: 'Summary of system, odour and noise compliance, dispersal, maintenance, and recommended conditions.',
    required: true,
    min_words: 150,
    max_words: 300,
    guidance:
      'Summarise system and key features. Confirm odour control per Defra guidance. Confirm noise compliance per BS 4142. Confirm discharge location adequacy. Confirm maintenance commitment. Confirm policy compliance. State recommended conditions.',
  },
];

export const VES_QUALITY: QualityCriteria = {
  min_policy_refs: 5,
  required_sections: [
    'Introduction',
    'Policy Framework',
    'Proposed Ventilation/Extraction System',
    'Odour and Noise Impact',
    'Discharge Location and Dispersal',
    'Maintenance Arrangements',
    'Conclusion',
  ],
  max_quality_score: 100,
};

export const VES_TEMPLATE = {
  assessment_type: 'Ventilation / Extraction Statement',
  short_name: 'VES',
  version: 1,
  sections: VES_SECTIONS,
  quality_criteria: VES_QUALITY,
};
