import type { AssessmentSection, QualityCriteria } from '@/types';

/**
 * Waste Management Strategy (Operational) -- required for major developments
 * and increasingly for all new-build applications to demonstrate that adequate
 * provision has been made for the storage, collection, and recycling of
 * operational waste during the life of the development.
 *
 * This document addresses operational waste management (during occupation),
 * not construction waste, which is covered in the Construction Management Plan.
 */

export const WMS_PROMPT = `You are preparing an Operational Waste Management Strategy (WMS) to accompany a planning application submitted to a local planning authority in England. The WMS demonstrates that the proposed development makes adequate provision for the storage, segregation, collection, and recycling of waste generated during the operational phase of the development.

## Document Purpose

The Waste Management Strategy must:
- Estimate the volume and type of waste that will be generated by the development during operation.
- Demonstrate that adequate internal and external waste storage has been provided, sized to the collection frequency and number of occupants/units.
- Demonstrate that storage areas are conveniently located for residents/occupiers and accessible for collection vehicles.
- Set out the recycling and waste segregation strategy.
- Describe the collection arrangements and confirm compatibility with the local authority waste collection service.
- Describe management responsibilities for communal waste facilities.
- Comply with local authority waste storage standards, Building Regulations Approved Document H6, and any adopted SPD.

## Key Policy and Guidance References

### National Planning Policy for Waste (2014)
- Paragraph 8: When determining planning applications, waste planning authorities should ensure that the likely impact of proposed, non-waste related development on existing waste management facilities, and on sites and areas allocated for waste management, is acceptable and does not prejudice the implementation of the waste hierarchy.
- All planning authorities should, to the extent appropriate to their responsibilities, ensure that new development makes sufficient provision for waste management.

### National Planning Policy Framework (NPPF, December 2023)
- **Paragraph 180**: Planning decisions should contribute to and enhance the natural and local environment.
- **Paragraph 185**: Planning policies and decisions should ensure that new development is appropriate for its location taking into account the likely effects of pollution.

### Building Regulations
- **Approved Document H6 (2015)**: Solid waste storage. Requires that adequate provision is made for the storage of solid waste in or in association with buildings. Sets minimum storage capacity requirements.
- Key requirements from AD H6:
  - Individual dwellings: space for a minimum of containers with capacity appropriate to collection frequency (typically 1 x 180L residual waste, 1 x 240L recycling, 1 x 23L food waste per dwelling for weekly collection; or larger for fortnightly).
  - Flats: communal storage calculated on the basis of litres per dwelling per week, with provision for residual waste, dry recycling, food waste, and bulky waste.
  - Storage areas should be within 30m carrying distance of the external door of each dwelling.
  - Collection vehicles should be able to approach within 25m of the storage point.

### Waste Hierarchy (Waste Framework Directive / Waste (England and Wales) Regulations 2011)
The waste hierarchy in order of preference:
1. **Prevention**: Reduce the quantity and harmfulness of waste.
2. **Preparing for re-use**: Repair, refurbish, reuse products.
3. **Recycling**: Turning waste into new substances or products.
4. **Other recovery**: Including energy recovery.
5. **Disposal**: Landfill or incineration without energy recovery (least preferred).

### Other Key References
- BS 5906:2005 Waste management in buildings -- Code of practice.
- Local authority waste and recycling collection schedules and accepted materials.
- Local authority waste storage and collection SPD or guidance notes.
- ADEPT Guidance on the Design of Residential and Commercial Waste Storage and Collection.
- London Plan Policy SI 7: Reducing waste and supporting the circular economy (London only).
- GLA Guidance on Waste Management in Residential Development (London only).

## Section-by-Section Guidance

### 1. Introduction (200-400 words)
- State the purpose of the WMS and the planning requirement.
- Identify the site and the proposed development: number of residential units (by type and bedroom count), commercial floor area (by use), or mixed-use composition.
- State the collection authority responsible for waste collection.
- Confirm the collection service arrangements (collection frequency, materials accepted, container types).
- Reference any local authority waste storage guidance or SPD that the strategy responds to.
- Outline the document structure.

### 2. Policy Framework (300-500 words)
- Set out the National Planning Policy for Waste (Paragraph 8).
- Set out the waste hierarchy and its relevance to the development.
- Reference Building Regulations Approved Document H6 and its requirements.
- Reference BS 5906 where applicable.
- Set out relevant local plan waste policies.
- Reference any adopted waste storage SPD or design guidance from the waste collection authority.
- For London: reference London Plan Policy SI 7 and GLA guidance.

### 3. Waste Generation Estimates (400-700 words)
- Estimate the waste generation rates for the development:
  - **Residential**: Use local authority or nationally recognised waste generation rates (typically 50-80 litres per dwelling per week for residual waste, similar for dry recycling, and 10-23 litres for food waste, depending on dwelling size and collection frequency).
  - **Commercial**: Estimate based on floor area and use type. Reference industry benchmarks (e.g., WRAP benchmarks for offices, retail, restaurants).
- Present a table showing:
  - Number of units/floor area by type.
  - Waste generation rate per unit/per m2.
  - Weekly waste generation volume by waste stream (residual, dry recycling, food waste, glass, garden waste).
  - Total weekly waste generation.
- Calculate the required storage capacity based on collection frequency:
  - If weekly collection: 1 week's capacity plus a margin for missed collections (typically 1.25x).
  - If fortnightly collection: 2 weeks' capacity plus margin.
- Convert to number and size of containers (e.g., 1,100L Eurobins, 660L bins, 360L bins, 240L bins, 180L bins).
- For commercial waste: distinguish between waste collected by the local authority (if eligible) and private commercial waste collection.

### 4. Storage and Collection Arrangements (500-1000 words)
#### 4.1 Residential Waste Storage
- **Individual houses**: Describe the bin storage provision for each dwelling:
  - Number and size of bins per dwelling.
  - Location of bin stores (front garden, side passage, rear garden, designated enclosure).
  - Screening and enclosure details (to avoid visual impact on the streetscene).
  - Carrying distance from dwelling to collection point (maximum 30m per AD H6).
  - Dragging distance from store to collection point (maximum 25m per AD H6 for crew assisted).

- **Flatted developments**: Describe the communal waste storage provision:
  - Location of communal bin stores (ground floor, basement, external courtyard).
  - Size of bin store (sufficient for the calculated number and size of containers plus access and manoeuvring space).
  - Ventilation and wash-down facilities.
  - Carrying distance from each dwelling to the bin store (maximum 30m per AD H6; maximum 50m where fire-protected internal routes exist).
  - Access arrangements for collection crews (door width, ramp gradients, turning space).

#### 4.2 Collection Vehicle Access
- Describe the collection vehicle route and access arrangements:
  - Vehicle type and dimensions (typically 11.2m long, 2.53m wide, 3.86m high refuse collection vehicle).
  - Access road width (minimum 3.7m for a RCV, with passing places on longer stretches).
  - Turning arrangements (swept path analysis for RCV turning movements, or reversing distance maximum 12m per NHBC guidance).
  - Distance from the collection vehicle stopping point to the bin store (maximum 25m for crew to pull bins).
  - Any requirement for management company or concierge to present bins at the collection point.
- Reference a swept path analysis (or note "[SWEPT PATH ANALYSIS TO BE APPENDED]").

#### 4.3 Commercial Waste Storage
- Where the development includes commercial units, describe:
  - Separate commercial waste storage area (distinct from residential).
  - Size and specification of the commercial bin store.
  - Collection arrangements (private contractor, collection frequency, vehicle access).
  - Waste types to be managed (depending on commercial use: food waste for restaurants, cardboard for retail, confidential waste for offices).

### 5. Recycling Strategy (300-500 words)
- Describe the recycling streams that will be provided:
  - Dry recyclables (paper, card, plastics, metals, glass -- as per local authority requirements).
  - Food waste (where separate food waste collection operates).
  - Garden waste (for houses with gardens).
  - Textiles collection point (for larger developments).
  - Electrical items collection or bulky waste storage (for flatted developments).
- Describe how residents will be informed about recycling:
  - Welcome packs with recycling information.
  - Signage on bin stores and containers.
  - Information from the management company.
  - Local authority recycling information and calendars.
- State the target recycling rate (typically aligned with the local authority target, commonly 50%+ of household waste).
- Describe any additional waste reduction measures:
  - Community composting facilities.
  - Reuse schemes (community swap shops, furniture reuse).
  - Circular economy initiatives.
- For larger developments, describe any on-site waste management facilities: compactors, balers, underground vacuum collection systems.

### 6. Management Responsibilities (200-400 words)
- For communal/flatted schemes:
  - Identify the responsible management entity (management company, residents' management company, housing association, estate management).
  - Describe the management obligations: bin rotation (presenting bins for collection and returning after collection), cleaning of bin stores, replacement of damaged bins, monitoring of contamination, enforcement of correct waste disposal.
  - Describe the maintenance schedule for bin stores (cleaning frequency, pest control, repair of ventilation and wash-down facilities).
- For mixed-use developments:
  - Describe the arrangements for managing both residential and commercial waste streams.
  - Confirm separation of residential and commercial waste management responsibilities.
- For phased developments:
  - Describe the interim arrangements during construction phases.
  - Confirm that permanent waste facilities will be operational before occupation of each phase.

### 7. Conclusion (200-300 words)
- Summarise the waste management arrangements.
- Confirm that storage provision meets or exceeds Approved Document H6 and local authority requirements.
- Confirm that collection vehicle access is adequate.
- Confirm that the recycling strategy supports the waste hierarchy.
- Confirm that management responsibilities are clearly defined.
- Confirm compliance with relevant planning policies.
- Note any planning conditions that the WMS is intended to discharge.

## Quality Standards

- Reference Building Regulations Approved Document H6 and its specific requirements.
- Reference BS 5906 where applicable.
- Reference the National Planning Policy for Waste and the waste hierarchy.
- Quantify waste generation rates and storage provision with specific numbers (litres, number of bins).
- Confirm carrying and dragging distances comply with AD H6 maximums (30m and 25m).
- Confirm collection vehicle access dimensions and turning requirements.
- Reference the local authority's waste collection arrangements (collection frequency, materials accepted).
- Present waste calculations in tabular format.
- Identify the management entity and their responsibilities.
- Professional waste management language; practical and implementable arrangements.
- Where local authority specific requirements are not known, flag as "[LOCAL AUTHORITY REQUIREMENTS TO BE CONFIRMED]".`;

export const WMS_SECTIONS: AssessmentSection[] = [
  {
    name: 'Introduction',
    description: 'Purpose, site, development, collection authority, and document structure.',
    required: true,
    min_words: 200,
    max_words: 400,
    guidance:
      'State the WMS purpose and planning requirement. Identify the site and development (units, floor areas). State the collection authority. Reference local waste guidance.',
  },
  {
    name: 'Policy Framework',
    description: 'National waste policy, waste hierarchy, Building Regulations, and local policies.',
    required: true,
    min_words: 300,
    max_words: 500,
    guidance:
      'Set out National Planning Policy for Waste. Describe the waste hierarchy. Reference AD H6. Reference BS 5906. List local plan waste policies and adopted SPDs.',
  },
  {
    name: 'Waste Generation Estimates',
    description: 'Waste arisings by stream, storage capacity calculation, and container requirements.',
    required: true,
    min_words: 400,
    max_words: 700,
    guidance:
      'Estimate waste generation (litres/dwelling/week or per m2). Present table of generation by waste stream. Calculate storage capacity based on collection frequency. Convert to container numbers and sizes.',
  },
  {
    name: 'Storage and Collection Arrangements',
    description: 'Bin store locations, dimensions, carrying distances, and collection vehicle access.',
    required: true,
    min_words: 500,
    max_words: 1000,
    guidance:
      'For houses: describe bin store per dwelling, screening, carrying distance (max 30m). For flats: describe communal bin stores, ventilation, wash-down, carrying distance. Describe collection vehicle access (RCV dimensions, road width, turning, dragging distance). For commercial: separate storage.',
    subsections: [
      {
        name: 'Residential Waste Storage',
        description: 'Individual and communal bin storage arrangements.',
        required: true,
        min_words: 250,
        max_words: 500,
        guidance: 'Describe storage for houses and/or flats. State bins per dwelling, store location, carrying distance, screening.',
      },
      {
        name: 'Collection Vehicle Access',
        description: 'RCV access route, dimensions, turning, and dragging distance.',
        required: true,
        min_words: 150,
        max_words: 350,
        guidance: 'Describe RCV type, road width, turning/swept path, distance from stop point to bin store.',
      },
      {
        name: 'Commercial Waste Storage',
        description: 'Separate commercial waste storage where applicable.',
        required: false,
        min_words: 100,
        max_words: 200,
        guidance: 'Describe separate commercial bin store, collection arrangements, and waste types.',
      },
    ],
  },
  {
    name: 'Recycling Strategy',
    description: 'Recycling streams, resident information, targets, and waste reduction measures.',
    required: true,
    min_words: 300,
    max_words: 500,
    guidance:
      'Describe recycling streams provided. Describe resident information (welcome packs, signage). State recycling target. Describe waste reduction measures. For larger schemes, describe on-site facilities.',
  },
  {
    name: 'Management Responsibilities',
    description: 'Management entity, obligations, maintenance, and phasing arrangements.',
    required: true,
    min_words: 200,
    max_words: 400,
    guidance:
      'Identify the management entity. Describe obligations (bin rotation, cleaning, replacement, contamination). Describe maintenance schedule. Address mixed-use and phased development arrangements.',
  },
  {
    name: 'Conclusion',
    description: 'Summary of provision, compliance, and policy confirmation.',
    required: true,
    min_words: 200,
    max_words: 300,
    guidance:
      'Summarise waste arrangements. Confirm AD H6 compliance. Confirm collection vehicle access. Confirm recycling strategy. Confirm management responsibilities. Note any planning conditions.',
  },
];

export const WMS_QUALITY: QualityCriteria = {
  min_policy_refs: 4,
  required_sections: [
    'Introduction',
    'Policy Framework',
    'Waste Generation Estimates',
    'Storage and Collection Arrangements',
    'Recycling Strategy',
    'Management Responsibilities',
    'Conclusion',
  ],
  max_quality_score: 100,
};

export const WMS_TEMPLATE = {
  assessment_type: 'Waste Management Strategy',
  short_name: 'WMS',
  version: 1,
  sections: WMS_SECTIONS,
  quality_criteria: WMS_QUALITY,
};
